"use client";
import React, { useEffect, useState } from "react";
import Accordion from "../../common-components/Accordion";

const policyDataEng = [
  {title:"Last updated on 19th December, 2024"
    ,desc:[
      {heading:"",points:["These terms and conditions are an electronic record in terms of Information Technology Act, 2000 and the rules thereunder (as applicable) and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures."]}
    ]},
  {
    title: "Introduction",
    desc: [
      {
        heading: "",
        points: [
          'Tata Payments Limited (“TPL” or “We” or “Our” or “Us”) having its registered office at Ground Floor, Army & Navy Building, 148, M G Road, Opposite Kala Ghoda, Fort, Mumbai, Maharashtra, Pin – 400001 and corporate office at Fort House, Dr. Dadabhai Naoroji Road, Fort, Mumbai, Maharashtra, Pin – 400001 is authorized by the Reserve Bank of India ("RBI") to issue and operate prepaid payment instruments in India in accordance with the provisions of the Master Directions on Prepaid Payment Instruments (PPIs) and the Payment and Settlement Systems Act, 2007, as amended from time to time.',
          "These terms and conditions (“Terms and Conditions” or “T&Cs”) set forth the terms that apply to you and/ or the Holder (collectively referred to as “You” or “Your”) who purchases and/ or uses the Gift PPI issued by Us. You agree that You have read the Terms and Conditions carefully before registering or accessing or purchasing or using the Gift PPI, if You do not agree to these Terms and Conditions or do not wish to be bound by these terms, You may not register, purchase, use or avail the Gift PPI from Us.",
          "You hereby consent to the collection, use, and disclosure of Your Registration Data (defined below) including your personal data in accordance with TPL’s Privacy Notice.",
          "You understand that We may amend the Terms and Conditions from time to time and shall post an updated version at TPL Site (defined below). The updated version of the Terms and Conditions shall take effect immediately upon posting. It is Your responsibility to review the Terms and Conditions periodically for any updates / changes made to these Terms and Conditions. If You continue to purchase and/ or use the Gift PPI after any changes have been made to these Terms and Conditions, it indicates Your acceptance and agreement to the updated Terms and Conditions, which may include additional terms, removal of certain sections or modifications. As long as You comply with these Terms and Conditions, We grant you a personal, non-exclusive, non- transferable, limited privilege to use TPL Site and/ or avail the services.",
        ]
      }
    ]
  },
  {
    title: "Eligibility",
    desc: [
      {
        heading: "",
        points: [
"You hereby represent and confirm that:",
"a)	You are a citizen/ resident of India;",
          "b)	You have attained a minimum of 18 (eighteen) years of age;",
          "c)	You are competent to enter into a legally binding agreement/ contract as per  the Applicable Law;",
          "d)	You have the right, authority and capacity to enter into this arrangement with us for availing the Gift PPI; ",
          "e)	You shall not impersonate any person or entity, or falsely state or otherwise misrepresent Your identity, age or affiliation with any person or entity;",
          "f)	You are not barred or otherwise legally prohibited from accessing or using the Gift PPI under the Applicable Law.",
          
          "If You do not meet Our eligibility requirements, You may not be able to avail the Gift PPI. You shall update Registration Data promptly upon any change so that it is always complete and accurate. In the event of any violation of the Terms and Conditions, TPL reserves the right to suspend or permanently prevent You from availing/ redeeming/ using the Gift PPI or the TPL Site."
          
        ]
      }
    ]
  },
  {
    title: "1.	Definitions",
    desc: [
      {
        heading: "",
        points: [
         " a)	“Applicable Law” shall mean all applicable laws, regulations, and legal requirements in force in India. For the avoidance of doubts, the expression Applicable Law shall include without limitation any guidelines, circulars, directives, or notifications issued by the RBI from time to time.",
"b)	“Holder” shall mean an individual or entity who obtains/ purchases the Gift PPI.",
"c)	“Gift PPI” shall mean a prepaid gift instrument issued in the form of card (physical or digital) by TPL in accordance with the PPI Master Direction that facilitate purchase of goods and services against the value stored therein. ",
"d)	“KYC Master Direction” refers to the ‘Master Direction – Know Your Customer (KYC) Direction, 2016’, as amended from time to time. ",
"e)	“Merchant” shall mean any establishment and/or entity who/ which accepts the Gift PPI as a payment instrument for online and/ or offline purchase of goods and services. ",
"f)	“PPI Master Direction” refer to the ‘Master Directions on Prepaid Payment Instruments (PPIs)’, as amended from time to time. ",
"g)	“Tata Neu Platform” shall mean the website and/ or the mobile application owned and operated by Tata Digital Private Limited, on which TPL Page is hosted. ",
"h)	“TPL Page” shall mean TPL hosted webpage and/ or a progressive web application (PWA) through which TPL enables users to avail/ purchase the Gift PPI.",
"i)	“TPL Site” shall mean any website, mobile application and/ or any other online platform owned or operated by TPL. TPL Site shall also include TPL Page on the Tata Neu Platform."
        ]
      }
    ]
  }
  ,
  {
    title: "2.	Purchase and Issuance of Gift PPIs",
    desc: [
      {
        heading: "",
        points: [
          "2.1	You may purchase the Gift PPI using the payment method as permitted under the Applicable Law and supported by TPL.",
         "2.2	Gift PPIs may only be purchased in denominations ranging from INR 10 up-to INR 10,000  or such other limits as may be permitted under the PPI Master Direction. Subject to the foregoing, You may decide on the amount or denomination you want to load onto the Gift PPI at the time of purchase. ",
          "2.3	Gift PPI(s) cannot be used to purchase another Gift PPI. ",
          "2.4	No interest shall be payable by TPL on the outstanding amount/ balance lying in the Gift PPI.",
          "2.5	In the event the Holder/ beneficiary of Gift PPI is not You, You shall ensure that the Holder/beneficiary is made aware of these Terms and Conditions at the time of sharing the Gift PPI.",
          "2.6	You can purchase the Gift PPI by providing a valid phone number (verified with one time password), self-declaration of the name, valid email address and any other additional information requested by TPL (“Registration Data”) that the PPI Master Direction and/ or the KYC Master Direction may prescribe to be necessary to satisfy the KYC requirements/ norms under the Applicable Law.",
          "2.7	Gift PPIs are issued by TPL in capacity of a prepaid payment instrument issuer in accordance with the PPI Master Direction. ",
          "2.8	Gift PPIs are usually issued instantly, however there may be delays in the system which may delay the issuance of Gift PPIs.",
          "2.9	Under no circumstances whatsoever, TPL shall accept the return of Gift PPIs once it is issued to You and/ or the Holder. ",
          "2.10	Gift PPIs issued by TPL are non-reloadable in nature and cannot be redeemed for cash . ",
          "2.11	You hereby  understands and acknowledges that the Gift PPI issued by TPL cannot be resold/exchanged/transferred for its value in cash, either in full or in part. ",
          "2.12	You can access information about your Gift PPI and validity via TPL Page.",
          "2.13 You can access information about your Gift PPI and validity via TPL Page."
          
          
        ]
      }
    ]
  },
  {
    title: "3.	Redemption and Validity of Gift PPI",
    desc: [
      {
        heading: "",
        points: [
          "3.1	Gift PPIs can only be redeemed towards purchase of eligible products and services on such Merchant platform/ establishment who facilitates the acceptance of such Gift PPIs.", 
          "3.2	Any purchases facilitated using the Gift PPI will get deducted from the Gift PPI balance, and any unused or the remaining balance will reflect on the Gift PPI after such deductions.",
          "3.3	You hereby agree to receive alerts for all transactions done using the Gift PPI on the contact details provided as Registration Data.",
          "3.4	Any unused Gift PPI balances may not be transferred to another Holder/ user.",
          "3.5	In the event, the Gift PPI has insufficient balance at the time of transaction, You may redeem the available balance lying in the Gift PPI and the remaining amount can be paid using a different payment method on the Merchant platform/establishment. The Gift PPI is valid for a period of 1 year from the date of issuance or such period as indicated in the Gift PPI. We will caution you regarding the impending expiry of your Gift PPI, during the 45 days’ period prior to expiry of the validity period of the Gift PPI, by sending a communication in this regard via on of the following mode of communications i.e. push notification, email, SMS, WhatsApp or any other mode.",
          "3.6	You may request for revalidation  of any expired Gift PPI. You hereby acknowledge and agree that any such revalidation shall be at the sole discretion of TPL.",
          "3.7	Redemption of balance in the Gift PPI is subject to the validity of the Gift PPI." 
          
        ]
      }
    ]
  },
  {
    title: "4.	Representation and Covenants ",
    desc: [
      {
        heading: "4.1	You hereby represent and covenant that:",
        points: [
         "(a)	You shall submit true, accurate and complete information/ Registration Data during the purchase of the Gift PPI.",
          "(b)	You hereby allow Us to collect and verify Your information/ Registration Data as per the requirements under the Applicable Law.",
          "(c)	You hereby consent and allow Us to store your Registration Data for a minimum period of 10 years from the date of expiry/ termination of the Gift PPI.",
          "(d)	You shall at all times keep the login credentials and the details of the Gift PPI strictly confidential (including but not limited to the Gift PPI number/ codes, PIN etc.) and shall not reveal the same to any person or entity. Any such disclosures made by You shall be at Your own risk without any recourse to Us.", 
          "(e)	You understand that We shall not be responsible if a Gift PPI is stolen, lost, used or destroyed which has been issued to You. In such events You must immediately report such loss or theft to Us and request immediate suspension of the Gift PPI. Once such reporting is made to Us, the Gift PPI can no longer be used, even if found subsequently.",
          "(f)	You understand and agree that if a transaction conducted using the Gift PPI is cancelled, the money will be refunded to the Gift PPI once the Merchant transfers such transaction amount. For any failed transaction where the amount gets debited from a Gift PPI will be reversed back to Your Gift PPI.",
          "(g)	You agree to comply with all Applicable Law (including the PPI Master Direction and KYC Master Direction) from time to time which govern the use of Gift PPI." 
          
        ]
      }
    ]
  },
  {
    title: "5.	Customer Service",
    desc: [
      {
        heading: "",
        points: [
"5.1.	In case You are unable to access the Gift PPI, please contact Us at customercare@tatapayments.com  and refer to our Customer Grievance Redressal Policy made available at TPL Site for further course of action. "
,"5.2.	In case of any unauthorised use of the Gift PPI, please immediately notify us at reportfraud@tatapayments.com and make a written request for blocking the Gift PPI issued to You."
,"5.3.	In the event You have any dispute with the Merchant in relation to the goods and services purchased from them, You must report the matter to the concerned Merchant. You understand that the Merchant shall be solely liable for the quality, merchantability, suitability, fitness and accuracy of all warranties for the product or services offered for sale on the Merchant platform/ establishment. We shall not be liable in any manner for the goods or services purchased by You from the Merchant nor We shall be made party to any such disputes. "
,          
        ]
      }
    ]
  },
  {
    title: "6. Indemnity and Limitation of Liability",
    desc: [
      {
        heading: "",
        points: [
         " 6.1.	You hereby agree to indemnify, defend and hold harmless TPL and its affiliates from and against any claims, costs, losses, damages, fines, penalties, interests, expenses arising out of or relating to the arrangement stipulated under these T&Cs including but on limited to purchase, use, misuse, redemption of the Gift PPI.",
"6.2.	Notwithstanding anything stated in these Terms and Conditions the aggregate liability of TPL to You from any cause whatsoever shall not in any event exceed the disputed transaction amount (made via the Gift PPI) or INR 10,000 (whichever is lower). ",
"6.3.	In no event shall TPL be liable for any special, incidental, indirect, or consequential loss or damage of any kind in connection with these Terms and Conditions, even if informed in advance of the possibility of such loss or damage."

        ]
      }
    ]
  },
  {
    title: "7.	Disclaimer and Force Majeure",
    desc: [
      {
        heading: "",
        points: [
"7.1.	We make no express or implied warranties or representations about our services in relation to Gift PPI. We disclaim any implied warranties including but not limited to warranties of merchantability or fitness of Gift PPI for a particular purpose. TPL makes no representation or warranty that the Gift PPI services shall always be accessible without interruption."
,"7.2.	We shall not be liable for any failure to perform any obligations under these Terms and Conditions, if the performance is prevented, hindered or delayed by a Force Majeure Event and in such case Our obligations shall stand suspended for so long as the Force Majeure Event continues. For the purpose of this clause “Force Majeure Event” shall mean any event arising due to any cause beyond the reasonable control of TPL including, without limitation, fire, flood, explosion, acts of God, civil commotion, pandemic, epidemic, lockdown, sabotage, strikes or industrial action of any kind, riots, insurrection, government legislation, war, internet failure, unavailability of IT/ communication system or acts of government etc."
        ]
      }
    ]
  },
  {
    title: "8.	Refund, Cancellation, Suspension and Termination ",
    desc: [
      {
        heading: "",
        points: [
          "8.1.	You understand that We reserve the right to cancel any Gift PPI if We suspect that there is duplicity of Gift PPI.",
          "8.2.	You understand that We reserve the right to suspend or terminate the Gift PPI with immediate effect and for an indefinite period, if We have reason to believe that the Registration Data or any other data provided by You is incorrect, false or misleading, or that the security of the Gift PPI has been compromised in any way. We also reserve the right to suspend or terminate the Gift PPI, if Your Registration Data is modified or changed and the same adversely impacts the usage of the Gift PPI.", 
          "8.3.	We reserve the right to suspend or terminate the Gift PPI for any reasons including but not limited to purchase of Gift PPI through fraudulent means, purchase/use of Gift PPI for an unlawful purpose misuse of Gift PPIs, and/or . pursuant to us receiving a statutory/regulatory direction in this regard.",
          "8.4.	You understand that We reserve the right to terminate/ suspend the transactions originating from Gift PPI or the Gift PPI services to You at any time with or without prior notice due to (i) any change in Our internal policy; or (ii) breach of these Terms and Conditions; or (iii) any change in requirements under the RBI guidelines/ regulations and/ or the Applicable Laws; and (iv) for any other reasons.", 
          "8.5.	All payments made using Gift PPI for mobile/ DTH recharge, bill pay, or any other payment processed by You on Tata Neu Platform or Merchants  shall be final and We will not be responsible for any error and omission by You or Merchants. Such transactions cannot be refunded, returned or cancelled once initiated.",
          "8.6.	If you erroneously processed a payment through Gift PII to an unintended Merchant or processed a payment for the wrong amount (for instance a typographical error at your end), Your only recourse will be to contact the Merchant directly to whom You have made the payment and ask them to refund the amount. We will neither be responsible to mediate such disputes, nor shall be liable to reimburse You or reverse such erroneous payment.",
          "8.7. You hereby understand and acknowledge that We will have the right to forfeit your Gift PPI (along with outstanding balance, if any) after three years from the expiry date of your Gift PPI."
        ]
      }
    ]
  },
  // {
  //   title: "Cancellation, Suspension and Termination",
  //   desc: [
  //     {
  //       heading: "",
  //       points: [
  //         "TPL reserves the right to cancel any Gift PPI suspected of duplicity.",
  //         "TPL may suspend or terminate Gift PPIs if Registration Data is incorrect or security is compromised.",
  //         "TPL may suspend or terminate Gift PPIs used for fraudulent, illegal, or unlawful purposes.",
  //         "TPL may terminate/suspend transactions or services due to policy changes, T&C breaches, regulatory changes, or other reasons.",
  //       ]
  //     }
  //   ]
  // },
 
  



  {
    title: "9. Governing Law and Jurisdiction",
    desc: [
      {
        heading: "",
        points: [
          "9.1	These Terms and Conditions are governed by and construed in accordance with the laws of India. ",
          "9.2	Any dispute, controversy or claim arising out of or in connection with these Terms and Conditions shall be amicably settled through mutual agreement by the parties (You and Us).",
          "9.3	If the dispute is not resolved amicably within a period of 30 days from the date of such dispute request, the matter shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996 as amended from time to time. The arbitration shall be presided over by a sole arbitrator mutually appointed by the Parties, and the proceedings shall be conducted in the English language. The venue and seat of arbitration shall be Mumbai. Each Party shall bear its own costs of the arbitration, unless awarded otherwise.", 
          "9.4	The courts at Mumbai shall have the exclusive jurisdiction over all disputes arising out of, or in relation to these Terms and Conditions and the use of Gift PPI." 
          
        ]
      }
    ]
  },
  {
    title: "10. Miscellaneous",
    desc: [
      {
        heading: "",
        points: [
          "10.1.	All charges and fees (if any) associated with the purchase of Gift PPI shall be disclosed at the time of purchase of the Gift PPI.    TPL may charge you a loading fee(s) based on the instrument of choice and the details of the charges shall be displayed to you upfront while loading the Gift PPI. A convenience fee (ranging from 0% to 3.5% (exclusive of any taxes)) is charged for credit-card based loading. The exact charges will be displayed to you before you complete the purchase.",

          "10.2.	You agree to receive promotional, transactional, service related and/ or any other caution advice/ alerts by email, SMS, or through any other means from time to time.",
          "10.3.	Cash-outs or fund transfers shall not be permitted for the Gift PPI.",
          "10.4.	No failure, delay or omission on part of TPL to exercise or enforce any rights under these Terms and Conditions will constitute a waiver of such rights or provisions. A waiver of any such right on one occasion will not constitute a waiver of any rights and remedies on future occasions.",
          "10.5.	If any provision or part of a provision of these Terms and Conditions is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms and Conditions and does not affect the validity and enforceability of any remaining provisions.",
          "10.6.	There is no joint venture, partnership, employment or agency relationship created between You and Us as a result of use of the TPL Site and/ or the Gift PPI.",
          "10.7.	You agree that these Terms and Conditions will not be construed against Us by virtue of having drafted them.",
          "10.8.	Except as otherwise expressly stated hereunder, a person who is not a party to these Terms and Conditions may not enforce any of the terms contained herein."
          
        ]
      }
    ]
  }
];


const policyDataMar= [
  {title:"19 दिसंबर 2024 रोजी शेवटचे अपडेट केले"
    ,desc:[
      {heading:"",points:["या अटी व नियम माहिती तंत्रज्ञान कायदा, २००० आणि त्याखालील नियम (लागू असल्याप्रमाणे) आणि माहिती तंत्रज्ञान कायदा, २००० द्वारे सुधारित केलेल्या विविध कायद्यांमधील इलेक्ट्रॉनिक रेकॉर्डशी संबंधित सुधारित तरतुदींनुसार इलेक्ट्रॉनिक रेकॉर्ड आहेत. हे इलेक्ट्रॉनिक रेकॉर्ड संगणक प्रणालीद्वारे तयार केले जाते आणि त्यावर कोणत्याही भौतिक किंवा डिजिटल स्वाक्षरीची आवश्यकता नसते.",
]}
    ]},
  {
    title: "परिचय",
    desc: [
      {
        heading: "",
        points: [
"टाटा पेमेंट्स लिमिटेड (“TPL” किंवा “आम्ही” किंवा “आमचे” किंवा “आमचे”), नोंदणीकृत कार्यालय - तळमजला, आर्मी आणि नेव्ही बिल्डिंग, 148, एमजी रोड, काळा घोडा, मुंबई, महाराष्ट्र, पिन - ४००००१ आणि कॉर्पोरेट कार्यालय - फोर्ट हाऊस, डॉ. दादाभाई नौरोजी रोड, फोर्ट, मुंबई, महाराष्ट्र, पिन - ४००००१, भारतीय रिझर्व्ह बँक ('RBI') द्वारे भारतात प्रीपेड पेमेंट इन्स्ट्रुमेंट जारी आणि संचालित करण्यासाठी, प्रीपेड पेमेंट इन्स्ट्रुमेंट्स (पीपीआय) आणि पेमेंट अँड सेटलमेंट सिस्टम्स ॲक्ट, २००७ च्या तरतुदींनुसार वेळोवेळी सुधारित केल्यानुसार अधिकृत आहे.",
"या 'अटी आणि नियमांमध्ये' तुम्हाला आणि/किंवा धारकाला (एकत्रितपणे 'तुम्ही' किंवा 'तुमचे' म्हणून संदर्भित) आमच्या द्वारे जारी केलेले 'गिफ्ट पीपीआय' खरेदी करताना आणि/किंवा वापरताना लागू होणाऱ्या अटी निश्चित करण्यात आल्या आहेत. तुम्ही सहमत आहात की तुम्ही नोंदणी करण्यापूर्वी किंवा ॲक्सेस करण्यापूर्वी किंवा 'गिफ्ट पीपीआय' खरेदी करण्यापूर्वी किंवा वापरण्यापूर्वी या अटी व नियम काळजीपूर्वक वाचले आहेत, जर तुम्ही या अटी आणि नियमांशी सहमत नसाल किंवा या अटींना बांधील राहण्याची तुमची इच्छा नसेल, तर तुम्ही आमच्याकडून 'गिफ्ट पीपीआय' नोंदणी, खरेदी करू शकत नाही किंवा त्यांचा वापर करू शकत नाही.",
"तुम्ही टीपीएलच्या प्रायव्हसी नोटीसनुसार, तुमच्या वैयक्तिक डेटासह तुमचा नोंदणी डेटा (खाली परिभाषित) गोळा करणे, वापरणे आणि प्रकट करणे याला संमती देत आहात.",
"तुम्ही सहमत आहात की, आम्ही अटी आणि नियमांमध्ये वेळोवेळी सुधारणा करू शकतो आणि अपडेटेड व्हर्जन टीपीएल साईटवर (खाली परिभाषित) पोस्ट करू. अटी आणि नियमांची अद्ययावत आवृत्ती पोस्ट केल्यानंतर लगेच लागू होईल. या अटी आणि नियमांमध्ये केलेल्या कोणत्याही अपडेटेशनसाठी/बदलांसाठी अटी आणि नियमांचे वेळोवेळी पुनरावलोकन करणे ही तुमची जबाबदारी आहे. जोपर्यंत तुम्ही या अटी आणि शर्तींचे पालन करत आहात, तोपर्यंत आम्ही तुम्हाला टीपीएल साईट वापरण्यासाठी आणि/किंवा सेवांचा लाभ घेण्यासाठी वैयक्तिक, अनन्य, गैर-हस्तांतरणीय, मर्यादित विशेषाधिकार देऊ.",    ]
      }
    ]
  },
  {
    title: "पात्रता",
    desc: [
      {
        heading: "",
        points: [
         
"तुम्ही याद्वारे प्रतिनिधित्व आणि पुष्टी करता की:",
"अ) तुम्ही भारताचे नागरिक/निवासी आहात;",
"ब) तुमचे वय किमान १८ (अठरा) वर्षे आहे;",
"क) तुम्ही लागू कायद्यानुसार कायदेशीर बंधनकारक करार करण्यास सक्षम आहात;",
"ड) 'गिफ्ट पीपीआय' चा लाभ घेण्यासाठी आमच्यासोबत या व्यवस्थेमध्ये प्रवेश करण्याचा अधिकार, अधिकार आणि क्षमता तुमच्याकडे आहे;",
"ई) तुम्ही कोणत्याही व्यक्तीची किंवा संस्थेची तोतयागिरी करणार नाही, किंवा खोटे सांगणार नाही किंवा अन्यथा तुमची ओळख, वय किंवा एखाद्या व्यक्तीशी किंवा संस्थेशी संलग्नता चुकीची मांडणार नाही;",
"एफ) तुम्हाला लागू कायद्यांतर्गत 'गिफ्ट पीपीआय' मध्ये प्रवेश करण्यापासून किंवा वापरण्यापासून प्रतिबंधित किंवा अन्यथा कायदेशीररित्या प्रतिबंधित केलेले नाही.",
"तुम्ही आमच्या पात्रता आवश्यकता पूर्ण न केल्यास, तुम्ही ‘गिफ्ट पीपीआय’ चे लाभ घेऊ शकणार नाही. तुम्ही नोंदणी डेटामध्ये कोणतेही बदल त्वरित अपडेट करणे आवश्यक आहे जेणेकरून ते नेहमी पूर्ण आणि अचूक असतील. अटी आणि नियमांचे उल्लंघन झाल्यास, 'गिफ्ट पीपीआय' किंवा टीपीएल साइटचा लाभ घेण्यापासून/रिडीम करण्यापासून/वापरण्यापासून तुम्हाला प्रतिबंधित करण्याचा किंवा कायमचे प्रतिबंध करण्याचा अधिकार टीपीएलने स्वतःकडे राखून ठेवलेला आहे.",
          
        ]
      }
    ]
  },
  {
    title: "१. व्याख्या",
    desc: [
      {
        heading: "",
        points: [
          

"अ) “लागू कायदा” म्हणजे भारतात लागू होणारे सर्व कायदे, नियम आणि कायदेशीर आवश्यकता. शंका टाळण्यासाठी, लागू होणाऱ्या कायद्यामध्ये आरबीआयने वेळोवेळी जारी केलेली कोणतीही मार्गदर्शक तत्त्वे, परिपत्रके, सूचना किंवा अधिसूचना मर्यादेशिवाय समाविष्ट आहेत.",
"बी) “धारक” म्हणजे ‘गिफ्ट पीपीआय’ प्राप्त/खरेदी करणारी कोणतीही व्यक्ती किंवा संस्था.",
"सी) “गिफ्ट पीपीआय” म्हणजे त्याच्या मूल्याइतक्या वस्तू आणि सेवांची खरेदी सुलभ करण्यासाठी पीपीआय मास्टर सूचनेनुसार टीपीएलद्वारे जारी केलेल्या कार्डच्या स्वरूपात (भौतिक किंवा डिजिटल) प्रीपेड गिफ्ट इन्स्ट्रुमेंट.",
"डी) “केवायसी मास्टर डायरेक्शन” म्हणजे ‘मास्टर डायरेक्शन – तुमचे ग्राहक जाणून घ्या (KYC) दिशानिर्देश, २०१६’, वेळोवेळी सुधारणा केल्याप्रमाणे.",
"इ) “मर्चन्ट” म्हणजे कोणतीही आस्थापना आणि/किंवा संस्था जी वस्तू आणि सेवांच्या ऑनलाइन आणि/किंवा ऑफलाइन खरेदीसाठी ‘गिफ्ट पीपीआय’ पेमेंटचे साधन म्हणून स्वीकारते.",
"एफ) “पीपीआय मास्टर डायरेक्शन” म्हणजे ‘प्रीपेड पेमेंट इन्स्ट्रुमेंट्स (PPIs) वरील मास्टर डायरेक्शन’ वेळोवेळी सुधारित केल्याप्रमाणे.",
"जी) “Tata Neu Platform” म्हणजे टाटा डिजिटल प्रायव्हेट लिमिटेडच्या मालकीची आणि ऑपरेट केलेली वेबसाइट आणि/किंवा मोबाइल ॲप्लिकेशन ज्यावर टीपीएल पेज होस्ट केलेले आहे.",
"एच) “टीपीएल पेज” म्हणजे टीपीएलने होस्ट केलेले वेबपेज आणि/किंवा प्रोग्रेसिव्ह वेब ऍप्लिकेशन (PWA) असा आहे, ज्याद्वारे टीपीएल युजर्सना 'गिफ्ट पीपीआय' घेण्यास/खरेदी करण्यास सक्षम करते.",
"आय) “टीपीएल साईट” म्हणजे कोणतीही वेबसाइट, मोबाईल ऍप्लिकेशन आणि/किंवा टीपीएलच्या मालकीचे किंवा ऑपरेट केलेले इतर कोणतेही ऑनलाइन प्लॅटफॉर्म. टीपीएल साईटमध्ये Tata Neu प्लॅटफॉर्मवरील टीपीएल पेज देखील समाविष्ट असेल.",
        ]
      }
    ]
  }
  ,
  {
    title: "२. 'गिफ्ट पीपीआय' ची खरेदी आणि ते जारी करणे",
    desc: [
      {
        heading: "",
        points: [
          

"२.१ तुम्ही लागू कायद्यानुसार परवानगी दिलेल्या आणि टीपीएलद्वारे समर्थित पेमेंट पद्धती वापरून 'गिफ्ट पीपीआय' खरेदी करू शकता.",
"२.२ 'गिफ्ट पीपीआय' केवळ १० ते १०,००० रुपयांच्या मूल्यांमध्ये किंवा पीपीआय मास्टर डायरेक्शन अंतर्गत परवानगी असलेल्या इतर मर्यादेत खरेदी केली जाऊ शकते. पूर्वगामीच्या अधीन राहून, तुम्ही खरेदीच्या वेळी ‘गिफ्ट पीपीआय’ वर लोड करावयाची रक्कम किंवा मूल्य ठरवू शकता.",
"२.३ ‘गिफ्ट पीपीआय’ इतर कोणतेही ‘गिफ्ट पीपीआय’ खरेदी करण्यासाठी वापरले जाऊ शकत नाही.",
"२.४ 'गिफ्ट पीपीआय' मध्ये असलेल्या थकबाकी रकमेवर/शिल्लकवर टीपीएल द्वारे कोणतेही व्याज देय होणार नाही.",
"२.५ 'गिफ्ट पीपीआय' चे धारक/लाभार्थी तुम्ही नसल्यास, 'गिफ्ट पीपीआय' शेअर करताना धारक/लाभार्थी यांना या अटी व शर्तींची जाणीव करून दिली आहे याची तुम्ही खात्री केली पाहिजे.",
"२.६ तुम्ही वैध फोन नंबर (वन टाइम पासवर्डने सत्यापित), नावाची स्व-घोषणा, वैध ईमेल पत्ता आणि टीपीएल (“नोंदणी डेटा”) द्वारे विनंती केलेली कोणतीही अतिरिक्त माहिती प्रदान करून 'गिफ्ट पीपीआय' खरेदी करू शकता, पीपीआय मास्टर डायरेक्शन आणि/किंवा केवायसी मास्टर डायरेक्शन लागू कायद्यानुसार केवायसी आवश्यकता/निकष पूर्ण करण्यासाठी हे आवश्यक असेल.",
"२.७ 'गिफ्ट पीपीआय' टीपीएलद्वारे पीपीआय मास्टर डायरेक्शननुसार प्रीपेड पेमेंट इन्स्ट्रुमेंट जारीकर्ता म्हणून त्याच्या क्षमतेनुसार जारी केले जाते.",
"२.८ ‘गिफ्ट पीपीआय’ सहसा तात्काळ जारी केले जातात, परंतु सिस्टीममध्ये विलंब होऊ शकतो ज्यामुळे ‘गिफ्ट पीपीआय’ जारी करण्यास विलंब होऊ शकतो.",
"२.९ कोणत्याही परिस्थितीत टीपीएल तुम्हाला आणि/किंवा धारकाला 'गिफ्ट पीपीआय' जारी केल्यानंतर ते परत स्वीकारणार नाही.",
"२.१० टीपीएलद्वारे जारी केलेले 'गिफ्ट पीपीआय' रीलोड करण्यायोग्य नाहीत आणि रोख रकमेसाठी रिडीम केले जाऊ शकत नाहीत.",
"२.११ तुम्ही समजता आणि कबूल करता की टीपीएलद्वारे जारी केलेले 'गिफ्ट पीपीआय' त्याच्या मूल्यासाठी संपूर्ण किंवा अंशतः रोख स्वरूपात पुनर्विक्री/बदली/हस्तांतरित केले जाऊ शकत नाही.",
"२.१२ तुम्ही तुमच्या 'गिफ्ट पीपीआय' आणि वैधतेबद्दल टीपीएल पेजद्वारे माहिती मिळवू शकता.",
          
        ]
      }
    ]
  },
  {
    title: "३. 'गिफ्ट पीपीआय'चे रिडम्प्शन आणि वैधता",
    desc: [
      {
        heading: "",
        points: [
          

"३.१ 'गिफ्ट पीपीआय' फक्त अशा व्यापारी प्लॅटफॉर्म/आस्थापनेवर पात्र उत्पादने आणि सेवांच्या खरेदीसाठी रिडीम केले जाऊ शकते जे अशा 'गिफ्ट पीपीआय ' स्वीकारण्याची सुविधा देतात.",
"३.२ ‘गिफ्ट पीपीआय’ वापरून केलेली कोणतीही खरेदी ‘गिफ्ट पीपीआय’ शिल्लकमधून वजा केली जाईल आणि अशा कपातीनंतर कोणतीही न वापरलेली किंवा उरलेली शिल्लक ‘गिफ्ट पीपीआय’ वर परावर्तित केली जाईल.",
"३.३ नोंदणी डेटा म्हणून प्रदान केलेल्या संपर्क माहितीवर ‘गिफ्ट पीपीआय’ वापरून केलेल्या सर्व व्यवहारांसाठी सूचना प्राप्त करण्यास तुम्ही सहमत आहात.",
"३.४ कोणतीही न वापरलेली ‘गिफ्ट पीपीआय’ शिल्लक इतर कोणत्याही धारक/वापरकर्त्याकडे हस्तांतरित केली जाऊ शकत नाही.",
"३.५ व्यवहाराच्या वेळी 'गिफ्ट पीपीआय' मध्ये पुरेशी शिल्लक नसल्यास, तुम्ही 'गिफ्ट पीपीआय' मधील उपलब्ध शिल्लक रिडीम करू शकता आणि व्यापारी प्लॅटफॉर्म/आस्थापनेवर इतर कोणत्याही पेमेंट पद्धतीचा वापर करून शिल्लक रक्कम भरू शकता. ‘गिफ्ट पीपीआय’ जारी केल्याच्या तारखेपासून १ वर्षाच्या कालावधीसाठी किंवा ‘गिफ्ट पीपीआय’ मध्ये दर्शविलेल्या कालावधीसाठी वैध आहे. 'गिफ्ट पीपीआय'ची वैधता कालावधी संपण्यापूर्वी ४५ दिवसांच्या कालावधीत, खालीलपैकी कोणत्याही एका कम्युनिकेशन चॅनेलद्वारे या प्रभावासाठी कम्युनिकेशन पाठवून आम्ही तुम्हाला तुमच्या 'गिफ्ट पीपीआय'च्या आगामी कालबाह्यतेबद्दल अलर्ट करू. जसे पुश नोटिफिकेशन, ईमेल, एसएमएस, व्हॉट्सॲप किंवा इतर कोणतेही माध्यम.",
"३.६ तुम्ही कालबाह्य झालेल्या 'गिफ्ट पीपीआय' च्या पुनर्प्रमाणीकरणासाठी विनंती करू शकता. तुम्ही कबूल करता आणि सहमत आहात की असे कोणतेही पुनर्प्रमाणीकरण टीपीएलच्या विवेकबुद्धीनुसार केले जाईल.",
"३.७ 'गिफ्ट पीपीआय' मधील शिल्लकीची पूर्तता 'गिफ्ट पीपीआय' च्या वैधतेच्या अधीन आहे.",
        ]
      }
    ]
  },
  
  {
    title: "४. प्रतिनिधित्व आणि नियम",
    desc: [
      {
        heading: "४.१ तुम्ही सहमत आहात की:",
        points: [
        


"(ए) 'गिफ्ट पीपीआय' खरेदी करताना तुम्ही खरी, अचूक आणि संपूर्ण माहिती/नोंदणी डेटा द्याल.",
"(बी) तुम्ही आम्हाला तुमची माहिती/नोंदणी डेटा संकलित करण्याची आणि लागू कायद्यातील आवश्यकतांनुसार सत्यापित करण्याची परवानगी देता.",
"(सी) तुम्ही आम्हाला गिफ्ट पीपीआय कालबाह्य झाल्याच्या तारखेपासून किमान १० वर्षांच्या कालावधीसाठी तुमचा नोंदणी डेटा संग्रहित करण्याची परवानगी देत आहात. ",
"(डी) तुम्ही लॉगिन क्रेडेन्शियल्स आणि गिफ्ट पीपीआय तपशील नेहमीच गोपनीय ठेवाल (गिफ्ट पीपीआय नंबर/कोड, पिन, इ. यासह परंतु इतकेच मर्यादित नाही) आणि ते कोणत्याही व्यक्ती किंवा संस्थेला उघड करणार नाही. तुमच्याद्वारे असा कोणताही खुलासा  तुमच्या स्वतःच्या जोखमीवर असेल, त्यामध्ये आमची काहीही जबाबदारी नाही. ",
"(ई) तुम्हाला दिलेले 'गिफ्ट पीपीआय' चोरीला गेले, हरवले, त्याचा गैरवापर झाला किंवा ते नष्ट झाले तर आम्ही जबाबदार राहणार नाही. अशा परिस्थितीत, तुम्ही अशा नुकसानीची किंवा चोरीची तात्काळ आमच्याकडे तक्रार करावी आणि ‘गिफ्ट पीपीआय’ तात्काळ रद्द करण्याची विनंती करावी. एकदा अशी सूचना आम्हांला दिल्यावर, ‘गिफ्ट पीपीआय’ परत मिळाले जरी तरी वापरता येणार नाही.",
"(एफ) तुम्ही सहमत आहात की ‘गिफ्ट पीपीआय’ वापरून केलेला कोणताही व्यवहार रद्द झाल्यास, मर्चन्टने अशा व्यवहाराची रक्कम हस्तांतरित केल्यानंतर पैसे ‘गिफ्ट पीपीआय’ मध्ये परत केले जातील. कोणत्याही अयशस्वी व्यवहारासाठी जिथे रक्कम ‘गिफ्ट पीपीआय’ मधून डेबिट केली जाते, ती रक्कम तुमच्या ‘गिफ्ट पीपीआय’ मध्ये परत केली जाईल.",
"(जी) तुम्ही ‘गिफ्ट पीपीआय’ च्या वापराला वेळोवेळी लागू असलेल्या सर्व कायद्यांचे (पीपीआय मास्टर डायरेक्शन आणि केवायसी मास्टर डायरेक्शनसह) पालन करण्यास सहमत आहात.",
          
        ]
      }
    ]
  },
  {
    title:  "५. ग्राहक सेवा",
    desc: [
      {
        heading: "",
        points: [
      
"५.१. तुम्ही 'गिफ्ट पीपीआय' मिळवण्यास, त्याचा वापर करण्यास असमर्थ असाल तर कृपया आमच्याशी customercare@tatapayments.com वर संपर्क साधा आणि पुढील कारवाईसाठी टीपीएल साईटवर उपलब्ध असलेल्या आमच्या ग्राहक तक्रार निवारण धोरणाचा संदर्भ घ्या.",
"५.२. ‘गिफ्ट पीपीआय’चा कोणताही अनधिकृत वापर झाल्यास, कृपया आम्हाला customercare@tatapayments.com वर त्वरित कळवा आणि तुम्हाला जारी केलेले ‘गिफ्ट पीपीआय’ ब्लॉक करण्याची लेखी विनंती करा.",
"५.३. मर्चन्टकडून खरेदी केलेल्या वस्तू आणि सेवांबाबत काही वाद असल्यास, संबंधित मर्चन्टला या प्रकरणाची सूचना द्या. तुम्हाला मान्य आहे की प्लॅटफॉर्म/आस्थापनेवर विक्रीसाठी ऑफर केलेली उत्पादने किंवा सेवांसाठी गुणवत्ता, व्यापारीता, योग्यता, योग्यता आणि अचूकतेच्या सर्व हमींसाठी मर्चन्ट पूर्णपणे जबाबदार असेल. तुम्ही मर्चन्टकडून खरेदी करता त्या वस्तू किंवा सेवांसाठी आम्ही कोणत्याही प्रकारे जबाबदार राहणार नाही किंवा आम्ही अशा कोणत्याही वादात सहभागी होणार नाही.",
          
        ]
      }
    ]
  },
  {
    title: "६. नुकसानभरपाई आणि दायित्वाची मर्यादा",
    desc: [
      {
        heading: "",
        points: [
          
       "६.१. तुम्ही सहमत आहात की, या अटी व नियमांतर्गत ठरवलेल्या व्यवस्थेतून उद्भवलेल्या किंवा त्याच्याशी संबंधित दावे, खर्च, नुकसान, दंड, व्याज, खर्चापासून टीपीएल आणि त्यांचे सहयोगी काहीही नुकसानभरपाई, बचाव देऊ लागत नाहीत. यामध्ये खरेदी, उपयोग, दुरुपयोग, 'गिफ्ट पीपीआय'चे रिडम्प्शन यांचा समावेश आहे, हे इतकेच मर्यादित नाही.",
"६.२. या अटी आणि शर्तींमध्ये काहीही असले तरी, कोणत्याही कारणास्तव टीपीएलची तुमच्यावर असलेली एकूण जबाबदारी विवादित व्यवहाराची रक्कम ('गिफ्ट पीपीआय' द्वारे केलेले) किंवा भारतीय रुपये १०,००० (जे कमी असेल) पेक्षा जास्त होणार नाही.",
"६.३. कोणत्याही परिस्थितीत टीपीएल, जरी अशा नुकसानीच्या किंवा नुकसानीच्या शक्यतेबद्दल आगाऊ सूचना दिली असली तरीही, या अटी व शर्तींच्या संदर्भात कोणत्याही विशेष, आनुषंगिक, अप्रत्यक्ष किंवा परिणामी नुकसान किंवा नुकसानीसाठी जबाबदार राहणार नाही.",
          

        ]
      }
    ]
  },
  {
    title:  "७. अस्वीकरण आणि असंभावित घटना ",
    desc: [
      {
        heading: "",
        points: [
        
"७.१. आम्ही ‘गिफ्ट पीपीआय’ च्या संबंधात आमच्या सेवांबद्दल कोणतीही स्पष्ट किंवा निहित वॉरंटी देत नाही किंवा प्रतिनिधित्व करत नाही. आम्ही अशा कोणत्याही निहित वॉरंटी नाकारतो, ज्यात विशिष्ट हेतूसाठी ‘गिफ्ट पीपीआय’ ची विक्री योग्यता किंवा उपयुक्ततेची वॉरंटी दिलेली असते, हे इतकेच मर्यादित नाही. टीपीएल कोणतेही प्रतिनिधित्व किंवा हमी देत नाही की ‘गिफ्ट पीपीआय’ सेवा नेहमी कोणत्याही व्यत्ययाशिवाय सहजसुलभ असतील.",
"७.२. या अटी व शर्तींच्या अंतर्गत कोणतेही दायित्व पार पाडण्यात अपयश आल्यास आम्ही जबाबदार असणार नाही, कोणत्याही असंभावित घटनेमुळे कार्य प्रदर्शन रोखले गेले, त्यामध्ये व्यत्यय किंवा विलंब झाल्यास, आम्ही जबाबदार राहणार नाही. आणि अशा परिस्थितीत जोपर्यंत असंभावित घटना कायम राहते तोपर्यंत आमच्या जबाबदाऱ्या स्थगित राहतील. या कलमाच्या उद्देशासाठी “फोर्स मॅजेअर” म्हणजे टीपीएलच्या वाजवी नियंत्रणाबाहेरील कोणत्याही कारणामुळे उद्भवणारी कोणतीही घटना, ज्यामध्ये कोणत्याही मर्यादेविना, आग, पूर, स्फोट, देवाचे कृत्य, नागरी गोंधळ, महामारी, साथीचे रोग, लॉकडाउन, तोडफोड यांचा समावेश होतो. , संप किंवा कोणत्याही प्रकारची औद्योगिक कारवाई, दंगल, बंड, सरकारी कायदा, युद्ध, इंटरनेट अपयश, आयटी/कम्युनिकेशन प्रणालीची अनुपलब्धता किंवा सरकारची कृती इत्यादी.",
        ]
      }
    ]
  },
  {
    title: "८. परतावा, रद्द करणे, निलंबन आणि समाप्ती",
    desc: [
      {
        heading: "",
        points: [
         ,
"८.१. तुम्ही समजता की गिफ्ट पीपीआयमध्ये डुप्लिकेशन असल्याची आम्हाला शंका असल्यास आम्ही कोणतेही गिफ्ट पीपीआय रद्द करण्याचा अधिकार राखून ठेवतो.",
"८.२. तुम्ही समजता की जर आमच्याकडे विश्वास ठेवण्याचे कारण असेल की तुमच्याद्वारे प्रदान केलेला नोंदणी डेटा किंवा इतर कोणताही डेटा चुकीचा, खोटा किंवा दिशाभूल करणारा आहे किंवा 'गिफ्ट पीपीआय'च्या सुरक्षिततेशी कोणत्याही प्रकारे तडजोड केली गेली आहे, तर आम्ही गिफ्ट पीपीआय सस्पेंड किंवा टर्मिनेट करण्याचा किंवा 'गिफ्ट पीपीआय' तात्काळ प्रभावाने आणि अनिश्चित काळासाठी बंद करण्याचा अधिकार राखून ठेवला आहे. तुमचा नोंदणी डेटा बदलला किंवा बदलला गेला असेल आणि त्याचा तुमच्या 'गिफ्ट पीपीआय' वापरावर विपरीत परिणाम होत असेल तर आम्ही 'गिफ्ट पीपीआय' रद्द करण्याचा अधिकार राखून ठेवतो.",
"८.३. आम्ही कोणत्याही कारणाने 'गिफ्ट पीपीआय' रद्द किंवा समाप्त करण्याचा अधिकार राखून ठेवतो, यामध्ये फसव्या मार्गाने 'गिफ्ट पीपीआय' ची खरेदी, बेकायदेशीर हेतूने 'गिफ्ट पीपीआय' ची खरेदी/वापर, 'गिफ्ट पीपीआय' चा गैरवापर आणि/किंवा आम्हाला या संदर्भात वैधानिक/नियामक सूचना मिळणे यांचा समावेश आहे, पण हे इतकेच मर्यादित नाही.",
"८.४. तुम्ही मान्य करता की, (i) आमच्या अंतर्गत धोरणातील कोणत्याही बदलामुळे; किंवा (ii) या अटी व शर्तींचे उल्लंघन; किंवा (iii) भारतीय रिझर्व्ह बँकेची मार्गदर्शक तत्त्वे/नियम आणि/किंवा लागू कायद्यांतर्गत आवश्यकतेमधील कोणत्याही बदलामुळे; आणि (iv) इतर कोणत्याही कारणामुळे 'गिफ्ट पीपीआय' किंवा 'गिफ्ट पीपीआय' सेवांबाबतचे तुमचे व्यवहार संपुष्टात आणण्याचा/निलंबित करण्याचा अधिकार आम्ही राखून ठेवतो, हे कोणत्याही वेळी आणि तुम्हाला इतर कोणत्याही कारणास्तव पूर्वसूचना देऊन किंवा न देता करता येऊ शकते.",
"८.५. मोबाइल/डीटीएच रिचार्ज, बिल पेमेंट, किंवा टाटा न्यू प्लॅटफॉर्म किंवा मर्चंटवर तुम्ही प्रक्रिया केलेले इतर पेमेंटसाठी 'गिफ्ट पीपीआय' वापरून केलेली सर्व देयके अंतिम असतील आणि तुमच्याद्वारे किंवा मर्चंटने केलेल्या कोणत्याही त्रुटी आणि चुकांसाठी आम्ही जबाबदार राहणार नाही. एकदा सुरू केल्यानंतर असे व्यवहार रिफंड केले जाऊ शकत नाहीत किंवा रद्द केले जाऊ शकत नाहीत.",
"८.६. जर तुम्ही चुकून एखाद्या अनोळखी मर्चन्टला गिफ्ट पीपीआयद्वारे पेमेंट केले असेल किंवा चुकीच्या रकमेसाठी पेमेंट प्रक्रिया केली असेल (उदा. तुमच्याकडून टायपोग्राफिकल एरर), तुम्हाला थेट मर्चन्टशी संपर्क साधावा लागेल आणि त्यांना रक्कम रिफंड देण्यास सांगावे लागेल. आम्ही अशा विवादांमध्ये मध्यस्थी करण्यासाठी जबाबदार असणार नाही किंवा आम्ही तुम्हाला परतफेड करण्यास किंवा अशी चुकीची देयके परत करण्यास जबाबदार असणार नाही.",
"८.७. तुम्ही सहमत आहात की आम्हाला तुमच्या 'गिफ्ट पीपीआय' च्या एक्सपायरी तारखेपासून तीन वर्षांनी तुमचे 'गिफ्ट पीपीआय' (थकबाकीसह, जर असेल तर) जप्त करण्याचा अधिकार आम्हाला आहे.",
        ]
      }
    ]

  },
 
  {
    title: "९. नियमन कायदा आणि अधिकार क्षेत्र",
    desc: [
      {
        heading: "",
        points: [
         "९.१ या अटी आणि शर्ती भारताच्या कायद्यांनुसार आहेत आणि त्यानुसारच त्यांचा अर्थ लावला जाईल. ",
"९.२ या अटी व शर्तींमुळे किंवा त्यांच्याशी संबंधित कोणताही वाद, विवाद किंवा दावे पक्षांमधील (तुम्ही आणि आम्ही) परस्पर कराराद्वारे सौहार्दपूर्णपणे सोडवले जातील.",
"९.३ जर विवाद त्याच्या तारखेपासून 30 दिवसांच्या आत सामंजस्याने सोडवला गेला नाही तर, वेळोवेळी सुधारणा केल्यानुसार लवाद आणि सामंजस्य कायदा, 1996 नुसार प्रकरण लवादाकडे पाठवले जाईल. लवादाचे अध्यक्षपद पक्षकारांनी परस्पर नियुक्त केलेला एकमेव मध्यस्थ असेल आणि कार्यवाही इंग्रजी भाषेत चालविली जाईल. लवादाचे ठिकाण मुंबई असेल. अन्यथा आदेश दिल्याशिवाय प्रत्येक पक्ष लवादाचा स्वतःचा खर्च उचलेल.",
"९.४ या अटी व शर्ती आणि 'गिफ्ट पीपीआय' च्या वापरामुळे उद्भवलेले किंवा त्यांच्याशी संबंधित सर्व विवाद मुंबईच्या न्यायालयांच्या विशेष क्षेत्रांधिकारांमध्ये सोडवले जातील.",
          
        ]
      }
    ]
  },
  {
    title: "१०) इतर",
    desc: [
      {
        heading: "",
        points: [
       "१०.१. गिफ्ट पीपीआयच्या खरेदीशी संबंधित सर्व चार्जेस आणि फी (जर असले तर) गिफ्ट पीपीआय खरेदीच्या वेळी उघड केले जातील. निवड केलेल्या साधनावर आधारित लोडिंग/सुविधा शुल्क(चे) (0% ते 3.5% (कोणतेही कर वगळून)) टीपीएल तुमच्याकडून आकारू शकते आणि गिफ्ट पीपीआय लोड करताना शुल्काचे तपशील तुम्हाला अगोदर दाखवले जातील. ",
"१०.२. तुम्ही सहमत आहात की प्रचारात्मक, व्यवहाराशी संबंधित, सेवेशी संबंधित आणि/किंवा इतर कोणताही सावधगिरीचा सल्ला/इशारे ईमेल, एसएमएस किंवा इतर कोणत्याही माध्यमातून तुम्हाला वेळोवेळी पाठवले जातील.",
"१०.३. गिफ्ट पीपीआयसाठी कॅश-आउट किंवा फंड ट्रान्सफरला परवानगी दिली जाणार नाही. तथापि, तुम्ही टीपीएलला गिफ्ट पीपीआयमधील निधी तुमच्या स्रोत खात्यात हस्तांतरित करण्याची विनंती करू शकता ज्यामधून असे इन्स्ट्रुमेंट लोड केले गेले होते.",
"१०.४. या अटी व शर्तींच्या अंतर्गत कोणत्याही अधिकारांचा वापर किंवा अंमलबजावणी करण्यात टीपीएलला अपयश, विलंब झाल्यास, ते अधिकार किंवा तरतुदी माफ होणार नाहीत.  कोणताही तरतुदीतून एकदा सूट दिली गेल्यास भविष्यातही ती सूट मिळेलच असे नाही.  ",
"१०.५. या अटी व शर्तींच्या तरतूदीतील कोणतीही तरतूद किंवा भाग बेकायदेशीर, निरर्थक किंवा लागू न करण्यायोग्य असल्याचे ठरवले गेले असल्यास, ती तरतूद किंवा तरतुदीचा भाग या अटी व शर्तींमधून वेगळा मानला जाईल आणि उर्वरित कोणत्याही तरतुदींच्या वैधतेवर आणि अंमलबजावणीवर त्याचा परिणाम होणार नाही. ",
"१०.६. टीपीएल साइट आणि/किंवा गिफ्ट पीपीआयच्या वापरामुळे तुम्ही आणि आमच्यामध्ये कोणतेही संयुक्त उपक्रम, भागीदारी, रोजगार किंवा एजन्सी संबंध निर्माण झालेले नाहीत.",
"१०.७. तुम्ही सहमत आहात की, या अटी आणि शर्तींचा मसुदा आम्ही तयार केल्यामुळे आमच्या विरुद्ध त्यांचा अर्थ लावला जाणार नाही.",
"१०.८. येथे स्पष्टपणे नमूद केल्याशिवाय, या अटी व शर्तींचा पक्ष नसलेली व्यक्ती येथे समाविष्ट असलेल्या कोणत्याही अटी लागू करू शकत नाही."
          
        ]
      }
    ]
  }
];



const policyDataHindi = [
  {
    title: "19 दिसंबर 2024 को आखरी बार अपडेट किया गया",
    desc: [
      {
        heading: "",
        points: [
         "ये नियम और शर्तें सूचना प्रौद्योगिकी अधिनियम, 2000 और उसके तहत नियमों (जैसा लागू हो) और सूचना प्रौद्योगिकी अधिनियम, 2000 द्वारा संशोधित विभिन्न क़ानूनों में इलेक्ट्रॉनिक रिकॉर्ड से संबंधित संशोधित प्रावधानों के अनुसार एक इलेक्ट्रॉनिक रिकॉर्ड हैं। यह इलेक्ट्रॉनिक रिकॉर्ड एक कंप्यूटर सिस्टम द्वारा तैयार किया गया है और इसके लिए किसी भौतिक या डिजिटल हस्ताक्षर की आवश्यकता नहीं है।",

        ]
      }
    ]
  },

  {
    title: "परिचय",
    desc: [
      {
        heading: "",
        points: [
       'टाटा पेमेंट्स लिमिटेड ("टीपीएल" या "हम" या "हमारा" या "हमें"), जिसका पंजीकृत कार्यालय ग्राउंड फ्लोर, आर्मी एंड नेवी बिल्डिंग, 148, एमजी रोड, काला घोड़ा के सामने, फोर्ट, मुंबई, महाराष्ट्र, पिन - 400001 में है और कॉर्पोरेट कार्यालय फोर्ट हाउस, डॉ. दादाभाई नौरोजी रोड, फोर्ट, मुंबई, महाराष्ट्र, पिन - 400001 में है, भारतीय रिज़र्व बैंक ("आरबीआई") द्वारा भारत में प्रीपेड भुगतान उपकरण जारी करने और संचालित करने के लिए अधिकृत है, जो प्रीपेड भुगतान उपकरणों (पीपीआई) और भुगतान और निपटान प्रणाली अधिनियम, 2007 पर मास्टर निर्देशों के समय-समय पर संशोधित किए गए प्रावधानों के अनुसार है।',
'ये नियम और शर्तें ("नियम और शर्तें" या "टीएंडसीएस") उन शर्तों को निर्धारित करती हैं जो आप और / या धारक (सामूहिक रूप से "आप" या "आपका" के रूप में संदर्भित) पर लागू होती हैं, जो हमारे द्वारा जारी किए गए ‘गिफ्ट पीपीआई’ को खरीदते हैं और / या उनका उपयोग करते हैं। आप सहमत हैं कि आपने ‘गिफ्ट पीपीआई’ को पंजीकृत करने या एक्सेस करने या खरीदने या उपयोग करने से पहले नियम और शर्तों को ध्यान से पढ़ा है, अगर आप इन नियमों और शर्तों से सहमत नहीं हैं या इन शर्तों से बंधे नहीं रहना चाहते हैं, तो आप हमसे ‘गिफ्ट पीपीआई’ को पंजीकृत, खरीद, उपयोग या प्राप्त नहीं कर सकते हैं।',
"आप टीपीएल की गोपनीयता सूचना के अनुसार अपने व्यक्तिगत डेटा सहित अपने पंजीकरण डेटा (नीचे परिभाषित) के संग्रह, उपयोग और प्रकटीकरण के लिए सहमति देते हैं।"
,"आप समझते हैं कि, हम समय-समय पर नियम और शर्तों में संशोधन कर सकते हैं और टीपीएल साइट (नीचे परिभाषित) पर एक अपडेटेड वर्जन पोस्ट करेंगे। नियम और शर्तों का अपडेटेड वर्जन पोस्ट करने के तुरंत बाद प्रभावी होगा। इन नियमों और शर्तों में किए गए किसी भी अपडेट / बदलाव के लिए समय-समय पर नियम और शर्तों की समीक्षा करना आपकी जिम्मेदारी है। जब तक आप इन नियमों और शर्तों का अनुपालन करते हैं, हम आपको टीपीएल साइट का उपयोग करने और/या सेवाओं का लाभ उठाने के लिए एक व्यक्तिगत, गैर-अनन्य, गैर-हस्तांतरणीय, सीमित विशेषाधिकार प्रदान करते हैं।"
        ]
      }
    ]
  },
  {
    title: "पात्रता",
    desc: [
      {
        heading: "",
        points: [
        "आप इस प्रकार प्रतिनिधित्व करते हैं और पुष्टि करते हैं कि:"
,"ए) आप भारत के नागरिक/निवासी हैं;"
,"बी) आपकी आयु कम से कम 18 (अठारह) वर्ष है;"
,"सी) आप लागू कानून के अनुसार कानूनी रूप से बाध्यकारी समझौता/अनुबंध करने में सक्षम हैं;"
,"डी) आपके पास ‘गिफ्ट पीपीआई’ का लाभ उठाने के लिए हमारे साथ इस व्यवस्था में प्रवेश करने का अधिकार, अधिकार और क्षमता है;"
,"इ) आप किसी व्यक्ति या संस्था का प्रतिरूपण नहीं करेंगे, या किसी व्यक्ति या संस्था के साथ अपनी पहचान, आयु या संबद्धता को गलत तरीके से नहीं बताएंगे या अन्यथा गलत तरीके से प्रस्तुत नहीं करेंगे;"
,"एफ) आपको लागू कानून के तहत ‘गिफ्ट पीपीआई’ तक पहुंचने या उसका उपयोग करने से प्रतिबंधित या अन्यथा कानूनी रूप से प्रतिबंधित नहीं किया गया है"
,
"यदि आप हमारी पात्रता आवश्यकताओं को पूरा नहीं करते हैं, तो आप ‘गिफ्ट पीपीआई’ का लाभ नहीं उठा पाएँगे। आपको पंजीकरण डेटा में किसी भी बदलाव पर तुरंत अपडेट करना होगा ताकि यह हमेशा पूर्ण और सटीक रहे। नियम और शर्तों के किसी भी उल्लंघन की स्थिति में, टीपीएल आपको ‘गिफ्ट पीपीआई’ या टीपीएल साइट का लाभ उठाने/रिडीम करने/उपयोग करने से निलंबित या स्थायी रूप से रोकने का अधिकार सुरक्षित रखता है।"
        ]
      }
    ]
  },
  {
    title: "1. परिभाषाएं",
    desc: [
      {
        heading: "",
        points: [
"ए) “लागू कानून” का अर्थ भारत में लागू सभी कानून, विनियम और कानूनी आवश्यकताएँ होंगी। संदेह न रहे इसके लिए, लागू कानून की अभिव्यक्ति में बिना किसी सीमा के आरबीआई द्वारा समय-समय पर जारी किए गए कोई भी दिशा-निर्देश, परिपत्र, निर्देश या अधिसूचनाएं शामिल होंगी।",
"बी) “धारक” का अर्थ है कोई व्यक्ति या संस्था जो ‘गिफ्ट पीपीआई’ प्राप्त करती/खरीदती है।",
"सी) “गिफ्ट पीपीआई” का अर्थ है पीपीआई मास्टर निर्देश के अनुसार टीपीएल द्वारा कार्ड (भौतिक या डिजिटल) के रूप में जारी किया गया प्रीपेड गिफ्ट साधन जो उसमें स्टोर्ड  मूल्य के विरुद्ध वस्तुओं और सेवाओं की खरीद की सुविधा प्रदान करता है।",
"डी) “केवाईसी मास्टर डायरेक्शन” का अर्थ है ‘मास्टर डायरेक्शन – अपने ग्राहक को जानें (केवाईसी) डायरेक्शन, 2016’, जिसे समय-समय पर संशोधित किया जाता है।",
"इ) “मर्चेंट” का अर्थ है कोई भी प्रतिष्ठान और/या संस्था जो वस्तुओं और सेवाओं की ऑनलाइन और/या ऑफ़लाइन खरीद के लिए भुगतान साधन के रूप में ‘गिफ्ट पीपीआई’ स्वीकार करती है।",
"एफ) 'पीपीआई मास्टर डायरेक्शन' का अर्थ समय-समय पर संशोधित 'प्रीपेड भुगतान उपकरणों (पीपीआई) पर मास्टर डायरेक्शन' से है। ",
"जी) 'टाटा नेउ प्लेटफॉर्म' का अर्थ टाटा डिजिटल प्राइवेट लिमिटेड की मालिकी की और उसके द्वारा संचालित वेबसाइट और/या मोबाइल एप्लिकेशन है, जिस पर टीपीएल पेज होस्ट किया गया है। ",
"एच) 'टीपीएल पेज' का अर्थ टीपीएल द्वारा होस्ट किया गया वेबपेज और/या प्रगतिशील वेब एप्लिकेशन (पीडब्ल्यूए) होगा, जिसके माध्यम से टीपीएल यूज़र्स को ‘गिफ्ट पीपीआई’ का लाभ उठाने/खरीदने में सक्षम बनाता है। ",
"आई) 'टीपीएल साइट' का अर्थ टीपीएल की मालिकी की या उसके द्वारा संचालित कोई भी वेबसाइट, मोबाइल एप्लिकेशन और/या कोई अन्य ऑनलाइन प्लेटफॉर्म होगा। टीपीएल साइट में टाटा नेउ प्लेटफॉर्म पर टीपीएल पेज भी शामिल होगा।",
        ]
      }
    ]
  },
  {
    title: "2. ‘गिफ्ट पीपीआई’ को खरीदना और जारी करना ",
    desc: [
      {
        heading: "",
        points: [
"2.1 आप लागू कानून के तहत अनुमत और टीपीएल द्वारा समर्थित भुगतान विधि का उपयोग करके ‘गिफ्ट पीपीआई’ खरीद सकते हैं। "
,"2.2 ‘गिफ्ट पीपीआई’ को केवल 10 रुपये से लेकर 10,000 रुपये तक के मूल्यवर्ग में या पीपीआई मास्टर डायरेक्शन के तहत अनुमत अन्य सीमाओं में खरीदा जा सकता है। पूर्वगामी के अधीन, आप खरीद के समय ‘गिफ्ट पीपीआई’ पर लोड की जाने वाली राशि या मूल्यवर्ग पर निर्णय ले सकते हैं।"
,"2.3 ‘गिफ्ट पीपीआई’ का उपयोग किसी अन्य ‘गिफ्ट पीपीआई’ को खरीदने के लिए नहीं किया जा सकता है"
,"2.4 ‘गिफ्ट पीपीआई’ में पड़ी बकाया राशि/शेष राशि पर टीपीएल द्वारा कोई ब्याज देय नहीं होगा।"
,"2.5 यदि ‘गिफ्ट पीपीआई’ का धारक/लाभार्थी आप नहीं हैं, तो आपको यह सुनिश्चित करना होगा कि धारक/लाभार्थी को ‘गिफ्ट पीपीआई’ साझा करते समय इन नियमों और शर्तों के बारे में अवगत कराया जाए।"
,'2.6 आप एक वैध फ़ोन नंबर (वन टाइम पासवर्ड से सत्यापित), नाम की स्व-घोषणा, वैध ईमेल पता और टीपीएल द्वारा अनुरोधित कोई अन्य अतिरिक्त जानकारी ("पंजीकरण डेटा") प्रदान करके ‘गिफ्ट पीपीआई’ खरीद सकते हैं, जिसे पीपीआई मास्टर डायरेक्शन और/या केवाईसी मास्टर डायरेक्शन लागू कानून के तहत केवाईसी आवश्यकताओं/मानदंडों को पूरा करने के लिए आवश्यक बता सकते हैं।'
,"2.7 ‘गिफ्ट पीपीआई’, पीपीआई मास्टर डायरेक्शन के अनुसार प्रीपेड भुगतान साधन जारीकर्ता की क्षमता में टीपीएल द्वारा जारी किए जाते हैं।"
,"2.8 ‘गिफ्ट पीपीआई’ आमतौर पर तुरंत जारी किए जाते हैं, लेकिन सिस्टम में देरी हो सकती है जिससे ‘गिफ्ट पीपीआई’ जारी करने में देरी हो सकती है।"
,"2.9 किसी भी परिस्थिति में, टीपीएल आपको और/या धारक को जारी किए जाने के बाद ‘गिफ्ट पीपीआई’ की वापसी स्वीकार नहीं करेगा।"
,"2.10 टीपीएल द्वारा जारी किए गए ‘गिफ्ट पीपीआई’ पुनः लोड करने योग्य नहीं हैं और उन्हें नकद में रिडीम नहीं किया जा सकता है।"
,"2.11 आप यह समझते हैं और स्वीकार करते हैं कि टीपीएल द्वारा जारी किए गए ‘गिफ्ट पीपीआई’ को उसके मूल्य के लिए नकद में, पूर्ण रूप से या आंशिक रूप से, पुनर्विक्रय/विनिमय/हस्तांतरित नहीं किया जा सकता है।"
,"2.12 आप टीपीएल पेज के माध्यम से अपने ‘गिफ्ट पीपीआई’ और वैधता के बारे में जानकारी प्राप्त कर सकते हैं"
        ]
      }
    ]
  },
  {
    title: "3. ‘गिफ्ट पीपीआई’ का रिडम्पशन और वैधता",
    desc: [
      {
        heading: "",
        points: [
          "3.1	‘गिफ्ट पीपीआई’ को केवल ऐसे मर्चेंट प्लेटफॉर्म/प्रतिष्ठान पर पात्र उत्पादों और सेवाओं की खरीद के लिए रिडीम किया जा सकता है जो ऐसे ‘गिफ्ट पीपीआई’ की स्वीकृति की सुविधा प्रदान करता है।"
          ,"3.2	‘गिफ्ट पीपीआई’ का उपयोग करके की गई कोई भी खरीद ‘गिफ्ट पीपीआई’ बैलेंस से काट ली जाएगी, और कोई भी अप्रयुक्त या शेष राशि ऐसी कटौती के बाद ‘गिफ्ट पीपीआई’ पर दिखाई देगी।"
          ,"3.3	आप पंजीकरण डेटा के रूप में दी गयी संपर्क जानकारी पर ‘गिफ्ट पीपीआई’ का उपयोग करके किए गए सभी लेन-देन के लिए अलर्ट प्राप्त करने के लिए सहमत हैं।"
          ,"3.4	किसी भी अप्रयुक्त ‘गिफ्ट पीपीआई’ शेष राशि को किसी अन्य धारक/उपयोगकर्ता को हस्तांतरित नहीं किया जा सकता है।"
          ,"3.5	यदि लेन-देन के समय ‘गिफ्ट पीपीआई’ में अपर्याप्त शेष राशि है, तो आप ‘गिफ्ट पीपीआई’ में मौजूद उपलब्ध शेष राशि को रिडीम कर सकते हैं और शेष राशि का भुगतान मर्चेंट प्लेटफॉर्म/प्रतिष्ठान पर किसी अन्य भुगतान विधि का उपयोग करके किया जा सकता है। ‘गिफ्ट पीपीआई’ जारी होने की तिथि से 1 वर्ष की अवधि या ‘गिफ्ट पीपीआई’ में दर्शाई गई अवधि के लिए वैध है। हम आपको ‘गिफ्ट पीपीआई’ की वैधता अवधि समाप्त होने से पहले 45 दिनों की अवधि के दौरान, आपके ‘गिफ्ट पीपीआई’ की इम्पेन्डिंग  समाप्ति के बारे में निम्नलिखित संचार माध्यमों में से किसी एक के माध्यम से इस संबंध में एक कम्युनिकेशन भेजकर सावधान करेंगे, जैसे पुश नोटिफिकेशन, ईमेल, एसएमएस, व्हाट्सएप या कोई अन्य माध्यम।"
          ,"3.6	आप किसी भी समाप्त हो चुके ‘गिफ्ट पीपीआई’ के पुनर्वैधीकरण के लिए अनुरोध कर सकते हैं। आप इस बात को स्वीकार करते हैं और सहमत हैं कि ऐसा कोई भी पुनर्वैधीकरण टीपीएल के पूर्ण अधिकार पर होगा।"
          ,"3.7	‘गिफ्ट पीपीआई’ में शेष राशि का रिडम्पशन ‘गिफ्ट पीपीआई’ की वैधता के अधीन है"
        ]
      }
    ]
  },
  {
    title: "4. प्रतिनिधित्व और नियम ",
    desc: [
      {
        heading: "4.1 आप अनुमति देते हैं कि:",
        points: [
,"(ए) आप गिफ़्ट पीपीआई की खरीद के दौरान सही, सटीक और पूर्ण जानकारी/पंजीकरण डेटा प्रस्तुत करेंगे।"
,"(बी) आप हमें लागू कानून के तहत आवश्यकताओं के अनुसार आपकी जानकारी/पंजीकरण डेटा एकत्र करने और सत्यापित करने की अनुमति देते हैं।"
,"(सी) आप गिफ़्ट पीपीआई की समाप्ति/समाप्ति की तारीख से कम से कम 10 वर्षों की अवधि के लिए आपके पंजीकरण डेटा को संग्रहीत करने के लिए सहमति देते हैं और हमें अनुमति देते हैं।"
,"(डी) आप हमेशा लॉगिन क्रेडेंशियल और गिफ़्ट पीपीआई के विवरण को पूरी तरह से गोपनीय रखेंगे (जिसमें गिफ़्ट पीपीआई नंबर/कोड, पिन आदि शामिल हैं, लेकिन इन्हीं तक सीमित नहीं हैं) और इसे किसी भी व्यक्ति या संस्था को नहीं बताएंगे। आपके द्वारा किया गया ऐसा कोई भी खुलासा हमारे किसी भी सहारे के बिना आपके अपने जोखिम पर होगा।"
,"(इ) आप समझते हैं कि अगर आपको जारी किया गया गिफ़्ट पीपीआई चोरी हो जाता है, खो जाता है, इस्तेमाल हो जाता है या नष्ट हो जाता है, तो हम इसके लिए ज़िम्मेदार नहीं होंगे। ऐसी स्थिति में आपको तुरंत हमें इस तरह के नुकसान या चोरी की रिपोर्ट करनी चाहिए और ‘गिफ्ट पीपीआई’ को तुरंत निलंबित करने का अनुरोध करना चाहिए। एक बार जब हमें इस तरह की रिपोर्ट की जाती है, तो ‘गिफ्ट पीपीआई’ का उपयोग नहीं किया जा सकता है, भले ही बाद में इसका पता चल जाए।"
,"(एफ) आप समझते हैं और सहमत हैं कि यदि ‘गिफ्ट पीपीआई’ का उपयोग करके किया गया कोई लेनदेन रद्द हो जाता है, तो मर्चेंट द्वारा ऐसी लेनदेन राशि हस्तांतरित करने के बाद पैसे ‘गिफ्ट पीपीआई’ को वापस कर दिए जाएंगे। किसी भी असफल लेनदेन के लिए जहां ‘गिफ्ट पीपीआई’ से राशि डेबिट हो जाती है, उसे आपके ‘गिफ्ट पीपीआई’ में वापस कर दिया जाएगा।"
,"(जी) आप समय-समय पर लागू होने वाले सभी कानूनों (पीपीआई मास्टर डायरेक्शन और केवाईसी मास्टर डायरेक्शन सहित) का पालन करने के लिए सहमत हैं जो ‘गिफ्ट पीपीआई’ के उपयोग को नियंत्रित करते हैं"

        ]
      }
    ]
  },
  {
    title: "5. ग्राहक सेवा",
    desc: [
      {
        heading: "",
        points: [
,"5.1. यदि आप ‘गिफ्ट पीपीआई’ तक पहुँचने में असमर्थ हैं, तो कृपया हमसे customercare@tatapayments.com पर संपर्क करें और आगे की कार्रवाई के लिए TPL साइट पर उपलब्ध हमारी ग्राहक शिकायत निवारण नीति देखें।"
,"5.2. ‘गिफ्ट पीपीआई’ के किसी भी अनधिकृत उपयोग के मामले में, कृपया हमें तुरंत customercare@tatapayments.com पर सूचित करें और आपको जारी किए गए ‘गिफ्ट पीपीआई’ को ब्लॉक करने के लिए लिखित अनुरोध करें।"
,"5.3. यदि आपके द्वारा व्यापारी से खरीदे गए सामान और सेवाओं के संबंध में कोई विवाद है, तो आपको संबंधित व्यापारी को मामले की रिपोर्ट करनी चाहिए। आप समझते हैं कि व्यापारी प्लेटफ़ॉर्म/प्रतिष्ठान पर बिक्री के लिए पेश किए गए उत्पाद या सेवाओं के लिए सभी वारंटियों की गुणवत्ता, व्यापारिकता, उपयुक्तता, फिटनेस और सटीकता के लिए पूरी तरह उत्तरदायी होगा। हम आपके द्वारा व्यापारी से खरीदे गए सामान या सेवाओं के लिए किसी भी तरह से उत्तरदायी नहीं होंगे और न ही हम ऐसे किसी भी विवाद में पक्षकार होंगे"
        ]
      }
    ]
  },
  {
    title: "6. क्षतिपूर्ति और देयता की सीम",
    desc: [
      {
        heading: "",
        points: [

          "6.1. आप इन नियमों और शर्तों के तहत निर्धारित व्यवस्था से उत्पन्न या उससे संबंधित किसी भी दावे, लागत, हानि, क्षति, जुर्माना, दंड, ब्याज, व्यय से टीपीएल और उसके सहयोगियों को क्षतिपूर्ति, बचाव और हानिरहित रखने के लिए सहमत हैं, जिसमें खरीद, उपयोग, दुरुपयोग, ‘गिफ्ट पीपीआई’ का रिडम्पशन शामिल है, लेकिन इन्हीं तक सीमित नहीं है।"
          ,"6.2. इन नियमों और शर्तों में बताई गई किसी भी बात के बावजूद, किसी भी कारण से टीपीएल की आपके प्रति कुल देयता किसी भी स्थिति में विवादित लेनदेन राशि (‘गिफ्ट पीपीआई’ के ज़रिए की गई) या 10,000 भारतीय रुपयों (जो भी कम हो) से ज़्यादा नहीं होगी।"
          ,"6.3. किसी भी स्थिति में टीपीएल इन नियमों और शर्तों के संबंध में किसी भी प्रकार के विशेष, आकस्मिक, अप्रत्यक्ष या परिणामी नुकसान या क्षति के लिए उत्तरदायी नहीं होगा, भले ही ऐसे नुकसान या क्षति की संभावना के बारे में पहले से सूचित किया गया हो।"
        ]
      }
    ]
  },
  {
    title: "7. अस्वीकरण और अप्रत्याशित घटनाए",
    desc: [
      {
        heading: "",
        points: [
          "7.1. हम ‘गिफ्ट पीपीआई’ के संबंध में अपनी सेवाओं के बारे में कोई स्पष्ट या निहित वारंटी या प्रतिनिधित्व नहीं करते हैं। हम किसी भी निहित वारंटी को अस्वीकार करते हैं, जिसमें किसी विशेष उद्देश्य के लिए ‘गिफ्ट पीपीआई’ की बिक्री योग्यता या उपयुक्तता की वारंटी शामिल है, लेकिन इन्हीं तक सीमित नहीं है। टीपीएल कोई प्रतिनिधित्व या वारंटी नहीं देता है कि ‘गिफ्ट पीपीआई’ सेवाएं हमेशा बिना किसी रुकावट के सुलभ रहेंगी"
          
          ,"7.2. हम इन नियमों और शर्तों के तहत किसी भी दायित्व को पूरा करने में किसी भी असफलता के लिए उत्तरदायी नहीं होंगे, अगर प्रदर्शन को किसी अप्रत्याशित घटना द्वारा रोका जाता है, बाधित किया जाता है या देरी की जाती है और ऐसे मामले में जब तक अप्रत्याशित घटना जारी रहती है, तब तक हमारे दायित्व निलंबित रहेंगे। इस खंड के उद्देश्य के लिए 'अप्रत्याशित घटना' का अर्थ किसी भी कारण से उत्पन्न होने वाली कोई भी घटना होगी जो टीपीएल के उचित नियंत्रण से परे हो, जिसमें बिना किसी सीमा के, आग, बाढ़, विस्फोट, ईश्वरीय कृत्य, नागरिक उपद्रव, महामारी, महामारी, लॉकडाउन, तोड़फोड़, हड़ताल या किसी भी प्रकार की औद्योगिक कार्रवाई, दंगे, विद्रोह, सरकारी कानून, युद्ध, इंटरनेट विफलता, आईटी/संचार प्रणाली की अनुपलब्धता या सरकार के कार्य आदि शामिल हैं"

        ]
      }
    ]
  },
  {
    title: "8.  रिफंड, रद्द करना, निलंबन और समाप्त",
    desc: [
      {
        heading: "",
        points: [

          "8.1. आप समझते हैं कि अगर हमें संदेह है कि ‘गिफ्ट पीपीआई’ में डुप्लिसिटी है तो हम किसी भी ‘गिफ्ट पीपीआई’ को रद्द करने का अधिकार सुरक्षित रखते हैं।",
          "8.2. आप समझते हैं कि अगर हमारे पास यह मानने का कारण है कि पंजीकरण डेटा या आपके द्वारा प्रदान किया गया कोई अन्य डेटा गलत, झूठा या भ्रामक है, या ‘गिफ्ट पीपीआई’ की सुरक्षा से किसी भी तरह से समझौता किया गया है, तो हम तत्काल प्रभाव से और अनिश्चित अवधि के लिए ‘गिफ्ट पीपीआई’ को निलंबित या समाप्त करने का अधिकार सुरक्षित रखते हैं। हम ‘गिफ्ट पीपीआई’ को निलंबित या समाप्त करने का अधिकार भी सुरक्षित रखते हैं, यदि आपका पंजीकरण डेटा संशोधित या परिवर्तित किया जाता है और इसका ‘गिफ्ट पीपीआई’ के उपयोग पर प्रतिकूल प्रभाव पड़ता है।",
          "8.3. हम किसी भी कारण से ‘गिफ्ट पीपीआई’ को निलंबित या समाप्त करने का अधिकार सुरक्षित रखते हैं, जिसमें धोखाधड़ी के माध्यम से ‘गिफ्ट पीपीआई’ की खरीद, गैरकानूनी उद्देश्य के लिए ‘गिफ्ट पीपीआई’ की खरीद/उपयोग, ‘गिफ्ट पीपीआई’ का दुरुपयोग, और/या इस संबंध में हमें एक वैधानिक/विनियामक निर्देश प्राप्त होने के बाद शामिल है, लेकिन इन्हीं तक सीमित नहीं है।",
          "8.4. आप समझते हैं कि हम (i) हमारी आंतरिक नीति में किसी भी बदलाव के कारण; या (ii) इन नियमों और शर्तों के उल्लंघन; या (iii) आरबीआई के दिशानिर्देशों/विनियमों और/या लागू कानूनों के तहत आवश्यकताओं में किसी भी बदलाव के कारण; और (iv) किसी भी अन्य कारणों से आपको ‘गिफ्ट पीपीआई’ या ‘गिफ्ट पीपीआई’ सेवाओं से होने वाले लेनदेन को किसी भी समय पूर्व सूचना के साथ या बिना समाप्त/निलंबित करने का अधिकार सुरक्षित रखते हैं।",
          "8.5.  मोबाइल/डीटीएच रिचार्ज, बिल भुगतान, या टाटा न्यू प्लेटफॉर्म या मर्चेंट पर आपके द्वारा संसाधित किसी भी अन्य भुगतान के लिए ‘गिफ्ट पीपीआई’ का उपयोग करके किए गए सभी भुगतान अंतिम होंगे और हम आपके या मर्चेंट द्वारा की गई किसी भी त्रुटि और चूक के लिए जिम्मेदार नहीं होंगे। एक बार शुरू होने के बाद ऐसे लेन-देन को रिफंड नहीं किया जा सकता या रद्द नहीं किया जा सकता।",
          "8.6. यदि आपने किसी अनजाने मर्चेंट को गिफ्ट पीआईआई के माध्यम से गलती से भुगतान प्रोसेस किया है या गलत राशि के लिए भुगतान प्रोसेस किया है (उदाहरण के लिए आपकी ओर से कोई टाइपोग्राफिकल त्रुटि), तो आपको सीधे उस मर्चेंट से संपर्क करना होगा, जिसे आपने भुगतान किया है और उनसे राशि वापस करने के लिए कहना होगा। हम न तो ऐसे विवादों में मध्यस्थता करने के लिए जिम्मेदार होंगे, न ही आपको प्रतिपूर्ति करने या ऐसे गलत भुगतान को उलटने के लिए उत्तरदायी होंगे।",
          "8.7. आप इस प्रकार समझते हैं और स्वीकार करते हैं कि आपके ‘गिफ्ट पीपीआई’ की समाप्ति तिथि से तीन साल बाद हमें आपके ‘गिफ्ट पीपीआई’ (बकाया शेष राशि के साथ, यदि कोई हो) को जब्त करने का अधिकार होगा"

        ]
      }
    ]
  },
  {
    title:  "9. शासकीय कानून और अधिकार क्षेत्",
    desc: [
      {
        heading: "",
        points: [
         
          ,"9.1 ये नियम और शर्तें भारत के कानूनों के अनुसार शासित हैं और उन्हीं के अनुसार उनकी व्याख्या की जाती हैं।",
          "9.2 इन नियमों और शर्तों से उत्पन्न या इनके संबंध में कोई भी विवाद, विवाद या दावा पार्टियों (आप और हम) द्वारा आपसी समझौते के माध्यम से सौहार्दपूर्ण ढंग से सुलझाया जाएगा।",
          "9.3 यदि विवाद उसकी तिथि से 30 दिनों के भीतर सौहार्दपूर्ण ढंग से हल नहीं होता है, तो मामले को समय-समय पर संशोधित मध्यस्थता और सुलह अधिनियम, 1996 के अनुसार मध्यस्थता के लिए भेजा जाएगा। मध्यस्थता की अध्यक्षता पार्टियों द्वारा पारस्परिक रूप से नियुक्त एकमात्र मध्यस्थ द्वारा की जाएगी, और कार्यवाही अंग्रेजी भाषा में आयोजित की जाएगी। मध्यस्थता का स्थान  मुंबई होगा। प्रत्येक पक्ष मध्यस्थता की अपनी लागत खुद करेगा, जब तक कि अन्यथा आदेश न दिया जाए।",
          "9.4 इन नियमों और शर्तों तथा ‘गिफ्ट पीपीआई’ के उपयोग से उत्पन्न होने वाले या उनसे संबंधित सभी विवादों का एकमात्र क्षेत्राधिकार मुंबई की अदालतें होंगी"

        ]
      }
    ]
  },
  {
    title:  "10. अन्य शर्ते",
    desc: [
      {
        heading: "",
        points: [
         
          "10.1. ‘गिफ्ट पीपीआई’ की खरीद से जुड़े सभी शुल्क और फीस (यदि कोई हो) का खुलासा ‘गिफ्ट पीपीआई’ की खरीद के समय किया जाएगा। टीपीएल आपसे आपके द्वारा चुने गए इंस्ट्रूमेंट के आधार पर लोडिंग/सुविधा शुल्क (0% से 3.5% (किसी भी कर को छोड़कर)) ले सकता है और शुल्क का विवरण ‘गिफ्ट पीपीआई’ लोड करते समय आपको पहले ही दिखा दिया जाएगा।"
          ,"10.2. आप समय-समय पर ईमेल, एसएमएस या किसी अन्य माध्यम से प्रचार, लेन-देन, सेवा से संबंधित और/या कोई अन्य सावधानी सलाह/अलर्ट प्राप्त करने के लिए सहमत हैं।"
          ,"10.3. ‘गिफ्ट पीपीआई’ के लिए नकद निकासी या फंड ट्रांसफर की अनुमति नहीं होगी। हालाँकि, आप टीपीएल से अनुरोध कर सकते हैं कि वह ‘गिफ्ट पीपीआई’ में पड़े फंड को आपके स्रोत खाते में स्थानांतरित कर दे, जहाँ से ऐसा इंस्ट्रूमेंट लोड किया गया था।"
          ,"10.4. इन नियमों और शर्तों के तहत किसी भी अधिकार का प्रयोग या उन्हें लागू करने में टीपीएल की ओर से कोई असफलता, देरी या चूक ऐसे अधिकारों या प्रावधानों का त्याग नहीं मानी जाएगी। एक अवसर पर ऐसे किसी भी अधिकार का त्याग भविष्य के अवसरों पर किसी भी अधिकार और उपचार का त्याग नहीं माना जाएगा।"
          ,"10.5. यदि इन नियमों और शर्तों के किसी प्रावधान या प्रावधान के किसी भाग को गैरकानूनी, शून्य या लागू न करने योग्य पाया जाता है, तो उस प्रावधान या प्रावधान के भाग को इन नियमों और शर्तों से अलग माना जाता है और यह किसी भी शेष प्रावधानों की वैधता और प्रवर्तनीयता को प्रभावित नहीं करता है।"
          ,"10.6. टीपीएल साइट और/या ‘गिफ्ट पीपीआई’ के उपयोग के परिणामस्वरूप आपके और हमारे बीच कोई संयुक्त उद्यम, साझेदारी, रोजगार या एजेंसी संबंध नहीं बनाया गया है।"
          ,"10.7. आप सहमत हैं कि इन नियमों और शर्तों को उनके ड्राफ्ट के आधार पर हमारे विरुद्ध नहीं माना जाएगा।"
          ,"10.8. नीचे अन्यथा स्पष्ट रूप से बताए गए को छोड़कर, कोई व्यक्ति जो इन नियमों और शर्तों का पक्षकार नहीं है, वह इसमें निहित किसी भी शर्त को लागू नहीं कर सकता है।"
          
        ]
      }
    ]
  }
];
const PolicyStatement = ({lang}) => {
  const [currentIndex, setCurrentIndex] = useState(null); // Changed to null instead of an empty string
  const [policyData,setPolicyData] = useState([])
  const handleAccordion = (value) => {
    // Fixed: Make sure value and currentIndex are numbers
    if (value === currentIndex) {
      setCurrentIndex(null);
    } else {
      setCurrentIndex(value);
    }
  };
  useEffect(()=>{
if(lang=="hindi"){
  setPolicyData(
    policyDataHindi
  )
}else if(lang=="marathi"){
  setPolicyData(
    policyDataMar
  )
}else{
  setPolicyData(
    policyDataEng
  )
}
  })
  return (
    <div className="px-[16px] py-[32px] lg:px-[149px] lg:py-[64px]">
      
      {policyData?.map((item, index) => {
        return (
          <>
           <Accordion
            key={index}
            question={item.title}
            isOpen={currentIndex === index} // Pass boolean value based on index match
            handleIsOpen={() => handleAccordion(index)} // Pass index directly
          >
            <div>
              {item?.desc?.map((list, listIndex) => {
                return (
                  <div key={listIndex}>
                    {list?.heading && (
                      <div className="text-[16px] lg:text-[18px] leading-[20px] lg:leading-[24px] font-semibold">
                        {list?.heading}
                      </div>
                    )}
                    <ul style={{ listStyleType: "disc", paddingLeft: "20px" }}>
                      {list?.points?.map((point, pointIndex) => {
                        return (
                          <p
                            key={pointIndex}
                            className="text-[14px] lg:text-[14px] leading-[20px] lg:leading-[20px] py-[10px]"
                          >
                            {point}
                          </p>
                        );
                      })}
                    </ul>
                  </div>
                );
              })}

              
            </div>
          </Accordion>
          {index < policyData.length - 1&&currentIndex !== index && (
              <hr className="border-t-[1px] border-[#DADADA] " />
            )}
          </>
         

        );
      })}
    </div>
  );
};

export default PolicyStatement;
