"use client";
import React, { useState } from "react";
import Accordion from "../../common-components/Accordion";

const policyData = [,
  {
    title: "Last updated: [November 3,2024]",
    desc: [
      {
        heading: "",
        points: [
        "These terms and conditions are an electronic record in terms of Information Technology Act, 2000 and the rules thereunder (as applicable) and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures."
        ]
      }
    ]
  },
  

  {
    title: "Introduction",
    desc: [
      {
        heading: "",
        points: [
          "Tata Payments Limited (\"Tata Payments\" or \"We\" or \"Our\" or \"Us\") having its registered office at Ground Floor, Army & Navy Building, 148, M G Road, Opposite Kala Ghoda, Fort, Mumbai, Maharashtra, Pin – 400001 and corporate office at Fort House, Dr. Dadabhai Naoroji Road, Fort, Mumbai, Maharashtra, Pin – 400001 is authorized by the Reserve Bank of India (\"RBI\") to operate as a 'Payment Aggregator' in India in accordance with the provisions of the Guidelines on Regulation of Payment Aggregators and Payment Gateways dated 17th March 2020 (\"PA Guidelines\"), as amended from time to time.",
          "These terms and conditions (\"General Terms\") along with the Privacy Notice (defined below) and the Special Terms (defined below) set forth the terms that apply to you (\"You\" or \"Your\") for Your usage of the Website. Before You may use the Website, You must read and accept all of these General Terms, Privacy Notice and the Special Terms (collectively referred to as \"Terms and Conditions\"). If You do not agree to these Terms and Conditions or do not wish to be bound by these terms, You may not register, or use Our Website.",
          "You hereby consent to the collection, use, and disclosure of Your registration data including your personal data in accordance with the Privacy Notice."
        ]
      }
    ]
  },
  {
    title: "1. Definitions",
    desc: [
      {
        heading: "",
        points: [
          "(a)	“Applicable Law” shall mean any statute, law, regulation, ordinance, rule, judgement, notification, rule of common law, order, decree, bye-law, government approval, directive, guideline, requirement or other governmental restriction, or any similar form of decision of, or determination by, or any interpretation, policy or administration, having the force of law of any of the foregoing, by any governmental authority having jurisdiction over the matter in question, whether in effect as of today or thereafter. For the avoidance of doubts, the expression Applicable Law shall include without limitation the PA Guidelines and any other guidelines, circulars, directives, notifications issued by the RBI from time to time.",

          "(b)	“Governmental Authority” means any national, state, provincial, local or similar government, governmental, regulatory or administrative authority, branch, agency, any statutory body or commission or any non-governmental regulatory or administrative authority, body or other organization to the extent that the rules, regulations and standards, requirements, procedures or orders of such authority, body or other organization have the force of Applicable Law or any court, tribunal, arbitral or judicial body, or any stock exchange in the territory with respect to a Party. For the avoidance of doubt, it is hereby clarified that, RBI shall be included in the definition of Governmental Authority for the purposes of these Terms and Conditions. ",
          
          "(c)	“Merchant” shall mean You or any other person/ entity who has opened a Merchant Account with Tata Payments for availing the Services and is governed by these Terms and Conditions.",
          
          "(d)	“Merchant Account” shall mean and refer to the account created by You for availing the Services.",
          
          "(e)	“Privacy Notice” shall mean the terms provided on the Website which governs the collection, processing and sharing of Your information/ personal data with Us.",
          
          "(f)	“Services” shall mean the payment aggregation/ gateway services and/ or any other payment solutions/ services provided by Us.",
          
          "(g)	“Special Terms” shall mean the agreement, memorandum of understanding, letter of intent, account opening form and/ or any other document entered between You and Us which governs the terms of use of Services.",
          
          "(h)	“Website” shall mean the website having domain name <a   style='color:blue' href= 'www.tatapayments.com'>www.tatapayments.com</a> and shall include mobile application and any other platform of Tata Payments.",
          
          
          
        ]
      }
    ]
  },
  {
    title: "2. Contents of Website",
    desc: [
      {
        heading: "",
        points: [
          "(a)	The Website is intended to provide information about Tata Payments, its affiliates, subsidiaries, group company, as well as the products and services offered/ provided by Us.",
          "(b)	The contents of the Website are proprietary to Tata Payments, its affiliates, subsidiaries group company, banking partners, technology service provider and similar entities. and You will not have any authority to claim any intellectual property rights, title, or interest in the contents of the Website and/ or the Services offered by Us. All trademarks used on the Website are the property of their respective owners.",
          "(c)	Nothing contained in this Website shall be construed as conferring any right whether express or implied by license or otherwise on any copyright, patent, trademark or other proprietary interest of Tata Payments or any third party. This Website and the content provided in this Website, including, but not limited to, text, graphics, images, audio, video, html code and buttons, may not be copied, reproduced, modified, republished, uploaded, posted, transmitted, or distributed in any way, without the prior written consent of Tata Payments."
        ]
      }
    ]
  },
  {
    title: "3. Registration for opening of Merchant Account",
    desc: [
      {
        heading: "",
        points: [
          "(a) You shall register to become a user of the Website only if You are of the age of 18 or above and can enter into binding contracts as per Applicable Laws. You are responsible for maintaining the secrecy of Your passwords, login credentials and the Merchant Account information.",
          "(b) You will be solely responsible for all use of the Website and/ or Services and shall not share Your password and login information with anyone else. You are responsible for maintaining the confidentiality of any login information and secure access credentials associated with the Merchant Account and shall be responsible for all activities in relation to the Merchant Account.",
          "(c) You also agree to provide true, accurate, current and complete information about Yourself as and when prompted by the Website. If You provide any information that is untrue, inaccurate, not updated or incomplete (or becomes untrue, inaccurate or incomplete), or We have reasonable grounds to suspect that such information is untrue, inaccurate, not updated or incomplete, We shall have the right to suspend or terminate Your Account and/or refuse any and all current or future use of the Website (or any portion thereof) or Services in connection thereto."
        ]
      }
    ]
  },
  {
    title: "4. Services",
    desc: [
      {
        heading: "",
        points: [
          "(a) You understand and agree that terms of use of Services will be governed in accordance with the Special Terms agreed between You and Us from time to time.",
          "(b) At the time of registration, you may be required to disclose the exact business category/ sub-category for which you will be using the Services and shall only avail such Services through Your designated website. You further agree that in order to use the Services for any other purpose, you shall notify Us in writing of such change and such change will be subject to approval from Us.",
          "(c) You shall not engage in any form of fraudulent transactions and use the Services for perpetrating a criminal offense or for sale of illegal/ prohibited products or services. Any scheme or structure to defraud the customer by You while using Services shall be reported to the relevant law enforcement authorities. You understand and agree that We also reserve the right to withdraw such Services in such a case."
        ]
      }
    ]
  },
  {
    title: "5. Onboarding and completion of KYC",
    desc: [
      {
        heading: "",
        points: [
          "(a)	You understand and agree that for providing the Services, We shall undertake due diligence measures and seek information required for carrying out Know Your Customer (“KYC”) from You. You further understand and agree that Tata Payments can undertake enhanced due diligence measures (including collection of any documentation), to satisfy itself relating to its due diligence requirements in line with the requirements and obligations under Applicable Law.",
          "(b) You understand and agree that Your onboarding with Tata Payments shall take place in accordance with Our 'Merchant Onboarding Policy' and 'Know Your Customer Policy' as well as guidelines prescribed by the RBI or any other regulatory authority from time to time.",
          "(c) You shall be required to submit to Us all the necessary documents and details as may be required by Us to complete Your onboarding journey in accordance with our policies and the Applicable Laws.",
          "(d) Your failure to share the required documents or details in accordance with our requirements shall entitle Us to put Your onboarding on hold. We may also refrain from providing access to the Services or the Website in the event, You fail to provide such documents/ details as required by Us."
        ]
      }
    ]
  },
  {
    title: "6. Integration with Tata Payments",
    desc: [
      {
        heading: "",
        points: [
         "(a)	You understand and agree that Tata Payments has integrated its Website with banking partners (including card networks), technology service provider (such as  payment gateways) and similar entities. The integration of Website is done in accordance with the documentation of the Application Programming Interface (‘API’) so provided by the financial institutions.",
         "(b)	You shall ensure that Your website and/ or the mobile application is secured in accordance with the prescribed guidelines under the Applicable Law from time to time. You shall not store any card data on Your website and/ or the mobile application. ",
         "(c)	You shall not integrate with Us for any Services or use any plugins or other software development kits unless You have completed the KYC and entered into an appropriate agreement with Us. In case, You choose to integrate Services without complying with the request in this clause, Your Services would be liable for termination by Us with immediate effect.",
         "(d)	Upon successful onboarding You shall be provided with the Merchant encryption key or an activation key for activation of the Services. You shall not share the encryption key or the activation key with any other person or use the activation key to activate integration on a website and/ or mobile application of any third party other than the website and/ or mobile application registered with Us by You."
        ]
      }
    ]
  },
  {
    title: "7. Use of Services/ Website by the Customer",
    desc: [
      {
        heading: "",
        points: [
          "(a)	You understand and agree that We will collect and process all or some of the personal data shared by You with Us or with the Merchant(s) with whom You have transacted using Our Services. ",

"(b)	You hereby authorise Us to share Your information with the banking partners, technology service providers and similar entities in connection with the transactions and the Services provided by Us. ",

"(c)	You understand and agree that in order to use the saved card feature on the Merchant website/ Website, Your card details shall be tokenised in accordance with the Applicable Law.",

"(d)	You may register/ de-register Your card (debit/ credit/ prepaid) on the Merchant website/ Website (as applicable) for a particular use in accordance with the Applicable Law. ",

"(e)	If You wish to request a refund for a successful transaction, You must contact the Merchant from whom You purchased the goods or services. The refund process will be subject to the terms and conditions agreed upon by You and the Merchant at the time of transaction on the Merchant  website.",

"(f)	You further understand and agree that We shall not be responsible for any delivery of products or services that You may have purchased from the Merchants. Additionally, We will not be liable for any post-sales services, customer invoices, customer inquiries, technical support, refunds etc. concerning the products or services You have purchased. ",

"(g)	Any customer grievance raised by You with Us shall be addressed in accordance with Our Customer Grievance Policy provided on Our Website."

        ]
      }
    ]
  },
  {
    title: "8. Compliance with RBI Guidelines",
    desc: [
      {
        heading: "",
        points: [
          "(a)	The Merchant shall during the entire term of the usage of the Services, implement, observe and comply with applicable requirements prescribed under Applicable Law.",
          "(b) The Merchant shall on their website and/ or the mobile application clearly indicate/ display to their customers:,", "(i) the general terms and conditions in relation to their website, terms of use, privacy, customer grievance etc.", " (ii) the return and refund policy for the products/ services offered for sale, including the timelines for processing such returns, refunds or cancellations.",
          "(c) The Merchant shall not store any data pertaining to the payment instrument / customer payment instrument credentials. Upon request from Us, the Merchant agrees to provide a written confirmation, in a form and manner acceptable to Us certifying compliance to this aspect.",
          "(d) The Merchant agrees to set up a comprehensive customer grievance redressal mechanism which provides the procedure for addressing complaints received from the customers and the Merchant shall include the details of the person designated by them for handling such customer complaints along with the turn-around time. It is clarified that such customer grievance redressal mechanism shall provide the facility to the customers for registering their complaints over phone, email, or any other electronic means.",
          "(e) During the entire duration of the usage of Services, the Merchant is required to adhere/ comply with the Payment Card Industry Data Security Standard (PCI-DSS) and the Payment Application Data Security Standard (PA-DSS). If the Merchant has engaged a payment gateway provider for availing payment solutions, the Merchant must ensure that such service provider also meets these certification requirements and provide evidence of compliance for Our records.",
          "(f)	The Merchant further agrees to comply with the RBI guidelines, rules, circulars, notifications including but not limited to PA Guidelines, guidelines on tokenisation, Master Directions on KYC etc. and/ or the Applicable Law."
        ]
      }
    ]
  },
  {
    title: "9. Relationship with You",
    desc: [
      {
        heading: "",
        points: [
          "The relationship between You and Tata Payments is on a principal-to-principal basis. Nothing contained herein shall be deemed to create any association, partnership, joint venture or relationship of principal and agent or master and servant, or employer and employee between Us hereto or any affiliates or subsidiaries thereof or to provide either party with the right, power or authority, whether express or implied to create any such duty or obligation on behalf of the other party."
        ]
      }
    ]
  },
  {
    title: "10. Confidentiality",
    desc: [
      {
        heading: "",
        points: [
          "(a) We and You agree that in connection with these Terms and Conditions, the receiving party shall not disclose to any third party any confidential information of the disclosing party that it may have access during and in connection with the Services and/ or these Terms and Conditions. 'Confidential Information' means all information or data of a confidential nature, software code, application, network configuration, documents, accounts, business plans, products, promotional and marketing plans, and processes and/or any other information in whole or in part of either party.",
          "(b) You further acknowledge that the Services may contain information which is designated confidential by Us and that You shall not disclose such information without Our prior written consent.",
          "(c) Notwithstanding the foregoing and for the avoidance of doubts, Tata Payments shall have right to disclose Confidential Information with any third-party including but not limited to its affiliates, subsidiaries, group company, banks, technology service provider and similar entities as may be required or necessary for the purposes of rendering the Services or performance of obligations under these Terms and Conditions.",
          "(d) The obligations set out in these Terms and Conditions shall not apply to Confidential Information which (i) at the time of the disclosure is or already was in the possession of the receiving party through legally permissible means or is in the public domain as evidenced (in each case) by written documents; or (ii) after the disclosure became generally available to the public through no fault of the receiving party; or (iii) was subsequently disclosed to the receiving party by a third party having a lawful right to disclose the information and being under no obligation of confidentiality with regard to the disclosing party; (iv) is required to be disclosed by the receiving party to comply with Applicable Laws or governmental regulations or an order of a competent court, provided that the receiving party provides prior written notice of such disclosure to the disclosing party and takes reasonable lawful actions to minimize the extent of disclosure."
        ]
      }
    ]
  },
  {
    title: "11. Intellectual Property Rights",
    desc: [
      {
        heading: "",
        points: [
          "(a) You acknowledge and agree that We own all rights, title and interest in and to the Services, including any intellectual property rights which subsist in the Services (whether registered or not).",
          "(b) Each party acknowledges that any trademarks used or adopted by You or Us in the conduct of its business operation is the sole property of the respective owners. Neither You or Us, under any circumstances, seek to register any trademark, business name, business processes, inventions, company name, domain name using or incorporating the intellectual property of the other.",
          "(c) Nothing contained herein shall authorize either You or Us to use, apply, invade or in any manner exploit or infringe the intellectual property rights of the other party without prior written consent of such party, and the usage shall be in compliance with these Terms and Conditions and/ or the agreement and such approval and policies as may be notified from time to time. In addition, You undertake not to infringe the intellectual property rights of any third party."
        ]
      }
    ]
  },
  {
    title: "12. Indemnity and Limitation of Liability",
    desc: [
      {
        heading: "",
        points: [
          "(a) You agree to indemnify and hold Tata Payments (and its officers, affiliates, group company, directors, agents and employees) harmless from any and against any and all claims, whether or not brought by third parties, causes of action, demands, recoveries, losses, damages, fines, penalties or other costs or expenses of any kind or nature, including reasonable attorneys' fees, or arising out of or related to Your breach of these Terms and Conditions, Your violation of any Applicable Laws or the rights of a third party, or Your use of the Website or any disputes between You and any third party.",
          "(b) Notwithstanding anything stated under this Agreement, the aggregate liability of Tata Payments to you from any cause whatsoever shall not in any event exceed the sum equivalent to the preceding one month's aggregate Service fees earned by Tata Payments under the agreement (entered between You and Us) from the date of occurrence of such liability. Tata Payments shall not be liable to you for any special, incidental, indirect or consequential damages, damages from loss of profits or business opportunities even if you have been advised in advance of the possibility of such loss, cost or damages."
        ]
      }
    ]
  },
  {
    title: "13. Force Majeure",
    desc: [
      {
        heading: "",
        points: [
          "Tata Payments shall not be liable for its failure to perform under these Terms and Conditions as a result of  force majeure event like act of god, epidemic, pandemic, fire, wars, sabotage, embargo, unavailability of any communication system, computer hacking, electronic viruses, malware, breach or unauthorised access to computer data and storage devices/ servers, computer crashes,  civil unrest, labour unrest, action of Governmental Authority, change in Applicable Laws, affecting the performance of Tata Payments, its banking partners, technology service providers and similar entities."
        ]
      }
    ]
  },
  {
    title: "14. Conflicting Terms",
    desc: [
      {
        heading: "",
        points: [
          "In the event of any conflict between the General Terms and Special Terms, the Special Terms shall prevail over the General Terms. To the maximum extent feasible, they shall be construed harmoniously."
        ]
      }
    ]
  },
  {
    title: "15. Disclaimer",
    desc: [
      {
        heading: "",
        points: [
          "(a) Notwithstanding anything stated elsewhere, You acknowledge that the Website, Services may not be uninterrupted or error-free or free from any virus or other malicious, destructive, or corrupting code, program, or macro and We disclaim all warranties, express or implied, written or oral, including but not limited to warranties of merchantability and fitness of the services for a particular purpose.",
          "(b) Tata Payments sole obligation and Your sole and exclusive remedy in the event of an interruption in Services, or loss of use and/or access to the Website/ Services shall be to use all reasonable endeavours to restore the Website/ Services as soon as reasonably possible."
        ]
      }
    ]
  },
  {
    title: "16.	Severability",
    desc: [
      {
        heading: "",
        points: [
          "If any provision or part-provision of these Terms and Conditions is or becomes invalid, illegal or unenforceable, the relevant provision or part-provision shall be deemed deleted and such invalid/ illegal/ unenforceable provision shall be replaced  by a valid, enforceable provision that best reflects the original intent. Any modification to or deletion of a provision or part-provision under this clause shall not affect the validity and enforceability of the rest of the Terms and Conditions. "
        ]
      }
    ]
  },
  {
    title: "17.	Amendment",
    desc: [
      {
        heading: "",
        points: [
          "We may update the content on the Website including these Terms and Conditions from time to time. All changes are effective immediately when We post them and apply to all access to and use of the Website thereafter. Your continued use of the Website and/ or the Services following the posting of revised Terms and Conditions means that You accept and agree to the changes. We encourage You to check these Terms and Conditions from time to time, so You are aware of any changes, as they are binding on You."
        ]
      }
    ]
  },
  {
    title: "18.	Waiver",
    desc: [
      {
        heading: "",
        points: [
          "No failure or delay by Us to exercise any right or remedy provided under these Terms and Conditions and/ or the Applicable Law shall constitute a waiver of that or any other right or remedy. No single or partial exercise of such right or remedy shall prevent or restrict the further exercise of that or any other right or remedy. Any waiver of any right or remedy shall only be effective if made in writing and executed by Us by Our authorized representative."
        ]
      }
    ]
  },
  {
    title: "19.	Governing Law and Jurisdiction",
    desc: [
      {
        heading: "",
        points: [
          "(a)	These Terms and Conditions are governed by the laws of India. All disputes and differences arising out of or in connection with these Terms and Conditions, if not resolved within thirty (30) days or other mutually agreed timeline between You and Us, shall be referred to the arbitration of a sole arbitrator appointed as per Applicable Law. The decision and award determined by such arbitration will be final and binding upon You and Us. The arbitration shall be conducted in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from time to time. The arbitration proceedings shall be conducted in English language and the venue of the arbitration shall be Mumbai."
        ,"(b)	You understand and agree that subject to the foregoing, the courts located in Mumbai shall have exclusive jurisdiction for disputes arising out of or in connection with these Terms and Conditions and/ or the Services. "]
      }
    ]
  }
]

const PolicyStatement = () => {
  const [currentIndex, setCurrentIndex] = useState(null); // Changed to null instead of an empty string

  const handleAccordion = (value) => {
    // Fixed: Make sure value and currentIndex are numbers
    if (value === currentIndex) {
      setCurrentIndex(null);
    } else {
      setCurrentIndex(value);
    }
  };
  return (
    <div className="px-[16px] py-[32px] lg:px-[149px] lg:py-[64px]">
      {policyData?.map((item, index) => {
        return (
          <>
            <Accordion
            key={index}
            question={item.title}
            isOpen={currentIndex === index} // Pass boolean value based on index match
            handleIsOpen={() => handleAccordion(index)} // Pass index directly
          >
            <div>
              {item?.desc?.map((list, listIndex) => {
                return (
                  <div key={listIndex}>
                    {list?.heading && (
                      <div className="text-[16px] lg:text-[18px] leading-[20px] lg:leading-[24px] font-semibold">
                        {list?.heading}
                      </div>
                    )}
                    <ul style={{ listStyleType: "disc", paddingLeft: "20px" }}>
                      {list?.points?.map((point, pointIndex) => {
                        return (
                          <p
                            key={pointIndex}
                            className="text-[14px] lg:text-[14px] leading-[20px] lg:leading-[20px] py-[10px]"
                            dangerouslySetInnerHTML={{ __html : point }}
                          >
                            
                          </p>
                        );
                      })}
                    </ul>
                  </div>
                );
              })}

             
            </div>
          </Accordion>
          {index < policyData.length - 1&&currentIndex !== index && (
              <hr className="border-t-[1px] border-[#DADADA] " />
            )}
          </>
        
        );
      })}
    </div>
  );
};

export default PolicyStatement;
